### ISSUE TITLE
Flashing the temperature till it reaches 50deg

### ISSUE THREAD

**Issue by Trezona** [Ralim/ts100#103]
Hi Ben, I’ve just noticed that in version 2 the flashing temperature runs to 30deg now and not 50deg as in version 1. Is there any reason for this? I did prefer 50deg.

**Comment by Ralim** [comment]
This was mostly me trying to simplify the code as I re-wrote it, so in a few places, I used the same constants for thresholds. This can be changed easily though :)

**Comment by Ralim** [comment]
This should be solved in Alpha 3 😄
