### ISSUE TITLE
Detailed view instead of Idle screen graphic (only)

### ISSUE THREAD

**Issue by csdpm** [Ralim/ts100#107]
The new idle screen graphic is very nice, but only really useful while getting used to the iron. It would be good if there was an option to change this to the Detailed view screen (as happens when advanced display is enabled) - but for that screen ONLY.

I'm finding that the Detailed view is too small for my aging eyes for the Sleep and Shutdown modes (too hard for me to see the temperature) So I would prefer to keep those modes as the simple display.

Having the detailed view for idle only provides useful information (set temp etc) even if I have to squint a bit.

Thanks.

 P.S. I like the ZZzz, but it would be nicer as Zzzz or a slightly smaller icon (sorry,picky). ;)
       **Edit:** For instance the universal standby icon eg. :
      https://www.iconexperience.com/_img/o_collection_png/green_dark_grey/512x512/plain/standby.png
      or even:
      https://cdn2.iconfinder.com/data/icons/power-symbol/512/power_symbol_14-512.png

**Comment by Ralim** [comment]
Hi,
This should be quite doable to implement for the next alpha of the firmware.
I can just split the setting into two, one for the idle screen and one for the soldering screens.

**Comment by csdpm** [comment]
That's perfect thank you!

You even did the Zzzz! :)
