### ISSUE TITLE
Boost setting tops out at 450 when using Fahrenheit with V2 alpha4

### ISSUE THREAD

**Issue by vince-br-549** [Ralim/ts100#111]
If I set Fahrenheit mode then boost should go up to 800 or so degrees no?

I set boost temp to highest it would go ... 450 ( F or C ?)
Then when I try to use it,  the temp drops from my set temp of 700 degrees F down.... Assuming it was
headed down to 450 F.

**Comment by Ralim** [comment]
Ah, yep. I'll fix this when I push out the next alpha shortly :)

**Comment by Ralim** [comment]
@vince-br-549 This should be patched in Alpha 5 hopefully :)
