### ISSUE TITLE
I cannot see the full menu ..

### ISSUE THREAD

**Issue by Vidalcris** [Ralim/ts100#125]
Just installed V2.0_fr and i cannot go after ADVIDL.. so i cannot access boost settings and more.
I even tried to reinstall the original firmware and install again V2.0 but the problem is still there.

Alpha 6 is working fine.

**Comment by Ralim** [comment]
Is the problem only present in the _fr version?

**Comment by Vidalcris** [comment]
Maybe yes.
I have to say i'm tired to have to do all the settings again on each flash ;)
This is why i just flashed alpha 6 XD

**Comment by Vidalcris** [comment]
Ok i confirm that the problem is not present with V2.0 (not french)

**Comment by ponchick** [comment]
Same issue with russian firmware. English version is Ok.

**Comment by PenGenKiddy** [comment]
@ponchick Yesterday i installed ru firmware. All works fine. Can you attach video with bug?

**Comment by ponchick** [comment]
@PenGenKiddy I downloaded and installed latest TS100_ru.hex (V2.0) from [releases page](https://github.com/Ralim/ts100/releases). ADVIDL is a last menu item, here is [video](https://www.dropbox.com/s/003y63r7uev76ai/2017-12-03%2011.51.19.mp4?dl=0).

**Comment by sotima** [comment]
Same here with german Version of Release 2.0 (TS100_de.hex). Menu does  only go to ADVIDL.
