### ISSUE TITLE
Unable to install ts100_de.hex

### ISSUE THREAD

**Issue by kartoffelbaer** [Ralim/ts100#129]
Hello,

when trying to install TS100_de.hex, I get the .err suffix, any idea how to find out what went wrong? The newest ts100.hex is working

kind regards

**Comment by Ralim** [comment]
Hello,
Do you mean that the english version works and the german version does not install?

Have you tried dragging the file onto the unit multiple times? Under some operation systems / computers it will install the firmware on the 2nd or 3rd attempt.

What computer are you using / OS etc ?

**Comment by Ralim** [comment]
@kartoffelbaer 
Hi,
Any update on this?

**Comment by sreichholf** [comment]
Hey, try renaming it to ts100.hex. Worked for me.
