### ISSUE TITLE
Tip temperature calibration sets tip temperature to 0

### ISSUE THREAD

**Issue by jonnieZG** [Ralim/ts100#137]
After performing a tip calibration, the tip temperature is displayed as 000 when the tip is not heated.

Shouldn't it be set to 24 degrees, that being an average room temperature?

**Comment by Ralim** [comment]
Hi,
The soldering iron contains a second temperature sensor inside the handle that is used for the calibration. Normally this is used for cold junction calibration. 

During calibration the temperature offset between the tips raw reading and this temperature is stored, then is subtracted when performing normal measurements.

The downside to this is that the tip temperature may be the same as the inside of the handle. Same as the official firmware.
