### ISSUE TITLE
Replace "by-character" scroll with "by-pixel" scroll

### ISSUE THREAD

**Issue by jonnieZG** [Ralim/ts100#140]
Using "by-pixel" scroll instead of "by-character" scroll, while increasing the overall scroll speed by cca 50% would increase readability. According to the http://www.displayfuture.com/Display/datasheet/controller/SSD1307.pdf manual, it seems feasible.

**Comment by Ralim** [comment]
This would actually be easier to implement in the LCD driver by supporting pixel offsets for the cursor positions rather than character slot positions.

Certainly a doable feature to add.
