### ISSUE TITLE
Autostart to sleep mode

### ISSUE THREAD

**Issue by Mrkvozrout** [Ralim/ts100#142]
I noticed that in the description of autostart there is described option S, meaning start in sleep mode.

> Automatically starts the iron into soldering on power up. T=Soldering, S= Sleep mode,F=Off

But only true/false can be set in settings and code on startup also does not count with the S option.

Is this a leftover from 1.x version?

- if yes - implementation is easy
- if no - translations should be updated

**Comment by Ralim** [comment]
Both?
In 1.x there were 3 modes, in 2.x there is only plan for the two modes as of current.
The third mode can be added if there is demand for it I guess? Its not hard to add.

**Comment by PeterFalken** [comment]
I think that it would be a good addition - it can make it safer if accidentally plugged in.

**Comment by Mrkvozrout** [comment]
@PeterFalken You mean safer in case you have explicitly selected to autostart to sleep temperature? I ask because autostart is disabled for default.

**Comment by PeterFalken** [comment]
Yes @Mrkvozrout.
Setting the autostart to sleep mode and having the sleep temperatura be lower than the active temperature would be an ideal safety measure. It allows the iron to warm up to the sleep temperature.

**Comment by SmayK** [comment]
hello yes my French translation is also based on this type of choice which is very good
for proof of my last correction
`/* Automatic start mode               */ "Choix de mode de démarage automatique à l'allumage <A=Activé, V=Mode Veille, D=Désactivé>",`
