### ISSUE TITLE
Scrolling should be faster

### ISSUE THREAD

**Issue by jonnieZG** [Ralim/ts100#152]
The new smooth scrolling looks great, but it is quite slow now. I think it should be at least 2x-3x the current speed. So either the pause between the frames should be reduced, or 2 (or even 3) instead of 1 column-per-frame shift should be used. 

Sorry, I haven't studied (yet) how the text display routine is implemented.

**Comment by Ralim** [comment]
Yeah, easy fix (either option).
Easy enough to add too, just wasn't sure how others perceived the speed.

**Comment by jonnieZG** [comment]
Yes, you should test both options, because I think reducing the pause might induce extra flickering.

**Comment by federck** [comment]
Is also possible to unify the scrolling method?
Descriptions appears "by line" and disappers "by character".

**Comment by jonnieZG** [comment]
Ok, the faster smooth scrolling is better now, but the letters now get torn in the middle. If you make a single shift by 2 instead of 1 px, and half the step time, I bet the tearing should significantly decrease.

**Comment by Ralim** [comment]
Already testing that right now on my unit.
Will be pushing in next release :)
