### ISSUE TITLE
Bad characters

### ISSUE THREAD

**Issue by jonnieZG** [Ralim/ts100#154]
Some characters, such as "ć" (as much as I can see for the Croatian translation) are displayed as a filled rectangle.

@Mrkvozrout, you said you too have the same issue with some characters in the high pages. From what I saw in issue #132, your EEPROM might be worn out and faulty, but my unit is brand new, and I strongly disbelieve that this is causing problems in my case. While all the characters look fine, "ć" is displayed as a filled rectangle. 

UTF-8 code for "ć" is c4 87, while "č" with the code c4 8d is displayed fine. I suspected that the reason might have been some signed/unsigned overflow in the bitmap pointer calculation, but as much as I can see from the STM32 documentation, char type is unsigned there... That's really strange. 

Does anyone else have an idea what is causing this issue?

**Comment by Ralim** [comment]
I doubt its the EEPROM, usually this is just a character pointer going wrong somewhere.

char type is uint8_t under the hood, and UTF is encoded in multibyte sequences.

Which language build is this appearing in and ill try and narrow it down :)

**Comment by jonnieZG** [comment]
Currently the problems were reported in Polish (for string "U0100 0Ā 1ā 2Ă 3ă 4Ą 5ą 6Ć 7ć 8Ĉ 9ĉ AĊ Bċ CČ Dč EĎ Fď") and for Croatian language. The Croatian translation does not use all the diacritic characters, so you can use this string to test all of them: "ČčĆćĐđŠšŽž".

**Comment by jonnieZG** [comment]
Possible causes also discussed in issue #170 .

**Comment by jonnieZG** [comment]
Works fine now! May I know what was causing the problem?

**Comment by Ralim** [comment]
An error where I had miscalculated the memory location for the settings structure and it was overwriting some of the font table.

**Comment by Mrkvozrout** [comment]
Updated czech translation with diacritics in #185. Works fine after the fix.
