### ISSUE TITLE
Italian bad characters and some other issue

### ISSUE THREAD

**Issue by federck** [Ralim/ts100#159]
All accented vocals (such as à and ù) are dispayed as uppercase letters.
Also «ADVSLD» option doesn't provide any description and «CAV VIN» shows "Display detailed information while soldering" description.

Is it possible to reduce the time for descriptions to come out?

Really big thanks for your great work,
Federico

**Comment by Ralim** [comment]
Thanks for flagging this with me, seems to be a few font issues for me to sort through on this latest release :/

Yes I will be reducing the time for the descriptions too :)

**Comment by Mrkvozrout** [comment]
This could be the wrong offset mentioned in #153 (because difference between lower and upper case is 32)

**Comment by Mrkvozrout** [comment]
The description positioning wrong in several other languages. See #166
