### ISSUE TITLE
One more when click when the settings help opens up to close it again

### ISSUE THREAD

**Issue by twikis** [Ralim/ts100#16]
Hi!

Thank you for this aaawesome firmware for this super cool iron! Just great, so excited to see even more features in the future!

Here's one little issue I found: Could you please add a second click when the help shows up, so that you don't have to a) change the value the help shows up for or b) jump to the next settings item when you didn't remember the value? It is pretty easy to get used to remembering the value that it was set to before the help shows up, but I just think it's slightly more convenient.

Cheers!

**Comment by Ralim** [comment]
Ah, yep.
Completely missed that issue last night. I'll get on it soon. 😄

**Comment by Ralim** [comment]
@twikis Just pinging you to let you know the newest release should fix this behaviour 😄
