### ISSUE TITLE
Using Teracopy results in .ERR file

### ISSUE THREAD

**Issue by jacobbjo** [Ralim/ts100#18]
Using Teracopy instead of the normal windows file copying will result in a error.

solution: 
Just drag the .hex with your right mouse button and select "copy here"

**Comment by Ralim** [comment]
Hi,
This is a known issue due to the way that terra copy and most other programs copy files.
Installing the firmware is only supported using the normal windows explorer.

This is not an issue in the firmware! This is an issue in the DFU bootloader that comes with the unit.
