### ISSUE TITLE
Detailed solder screen not working

### ISSUE THREAD

**Issue by Apollomark** [Ralim/ts100#181]
The detailed screen whilst soldering doesn't seem to work on my iron, works on idle though (version 2.01) Am I doing something wrong? Both values set to "T" to activate the detailed screens on both soldering and idle.

**Comment by Ralim** [comment]
There currently isn't actually a designed screen for while you solder, just sleeping and idle at the moment.

What would you like to see while soldering and I'll make one :)

**Comment by Apollomark** [comment]
Hello
I was expecting the battery voltage, tip temperature same as the idle screen when iron is cooling.
I think it's brilliant how you have improved and continue to improve the iron with continuous software updates.
Thanks
Mark.


On 1 Jan 2018, at 00:38, Ben V. Brown <notifications@github.com<mailto:notifications@github.com>> wrote:


There currently isn't actually a designed screen for while you solder, just sleeping and idle at the moment.

What would you like to see while soldering and I'll make one :)
