### ISSUE TITLE
Include some example boot up logo files

### ISSUE THREAD

**Issue by Lenbok** [Ralim/ts100#182]
It would be nice if there were a few nice example boot up logo files that the lazy/unartistic among us could just directly flash :-).

**Comment by Ralim** [comment]
If anyone out there has any to donate I'm happy to add them to the repository.
Haven't really made any myself that I like :)

**Comment by JohnEdwa** [comment]
Nothing beats some good old [Chinglish from the marketing material](//img.banggood.com/images/upload/2015/12/552/1.jpg).

![splash_1](https://i.imgur.com/qMAIx2u.png)

![splash_2](https://i.imgur.com/vHbbTEr.png)

Sadly "After 10000 times Striking Test Still Steadfast" and "When You're Not Here, He's Waiting For you Quietly" are too long to fit properly ;(

**Comment by Schattenbanane** [comment]
I spend some time creating something clean and vaguely "officially-looking".
![ts100_logo](https://user-images.githubusercontent.com/8728659/34654941-ffa2a0a0-f402-11e7-8b05-135da8e07426.png)
If somebody wants to use it they are welcome to do so.

**Comment by wortex1979** [comment]
schattenbanane very good logo

**Comment by jonnieZG** [comment]
Here's mine. However, I'm not sure whether is it legal to use their logo in the custom software. 

![logomini](https://user-images.githubusercontent.com/8830300/34663810-03435398-f459-11e7-8b38-006c97ee5e9e.png)

**Comment by SmayK** [comment]
here is my image idea
<a href="http://zupimages.net/viewer.php?id=18/11/y6wp.bmp"><img src="https://zupimages.net/up/18/11/y6wp.bmp" alt="" /></a>

**Comment by federck** [comment]
Mine here:

![horrorvacuielectronics2](https://user-images.githubusercontent.com/33298498/38165482-647ac820-3514-11e8-8d8c-e296db4c1b11.png)

![tantostagno](https://user-images.githubusercontent.com/33298498/38165484-64bf4202-3514-11e8-9347-b3ead2fe9215.png)

**Comment by River-b** [comment]
would be awesome if all these other Custom logos could go into central place in Github so people could find them easier to browse for one they like.

**Comment by River-b** [comment]
> Mine here:
> 
> ![horrorvacuielectronics2](https://user-images.githubusercontent.com/33298498/38165482-647ac820-3514-11e8-8d8c-e296db4c1b11.png)
> 
> ![senzanome](https://user-images.githubusercontent.com/33298498/38167224-1e4a0348-3532-11e8-9a7b-a3c6496cd51b.jpg)
> 
> ![tantostagno](https://user-images.githubusercontent.com/33298498/38167142-b966e186-3530-11e8-9036-008d7334140e.png)

I like your Boot Logos I'm going to convert them to DFU  for Pinecil :)    do you have any more let me know

**Comment by River-b** [comment]
This is my first Logo Art ever 
Doggie Bone
![doggie_bone](https://user-images.githubusercontent.com/97197236/153775473-b5449ed9-9c28-480f-af95-6153ba3f8bd2.png)

I could not attach the DFU in here, but just convert that image using the Python script in the Boot Logos folder.
