### ISSUE TITLE
!Hot Iron! with no display bug

### ISSUE THREAD

**Issue by stray77** [Ralim/ts100#19]
I finished soldering some stuff and I'm holding a 320C iron.  I press both a+b (not in idle mode) and the display says cool (thermometer mode) and the temp starts falling...good so far.  I place the iron down.  After a few minutes the display goes out (I assumed the unit is off).  At this point I pick it up again and I press the button closest to the tip, no response from the display.  I assume it's still off.  I place it down again.  Moments later I am surprised to see smoke rising from the tip.  The iron is hot with no display.  I pick it up again try both buttons, neither activate the screen so I unplug it.   I then repeated this sequence to confirm it is reproducible.  I can only assume you want the display on any time the iron is on and will want to address this.

1. press the button closest to the tip, let it heat for a few seconds.
2. press both buttons to enter thermometer mode 'cool' will be displayed
3. place it down
4. wait for display to go out
5. press the button closest to the tip.

The iron will heat up with no display.

**Comment by Ralim** [comment]
That is indeed a serious bug I'll need to check out.
Should get back to you on this within 12 hours with a fix if I can verify this.
Thank you for reporting
