### ISSUE TITLE
Intel HEX files vs DFU and logos

### ISSUE THREAD

**Issue by Mrkvozrout** [Ralim/ts100#198]
Currently there is no way to remove existing logo. In #197 I added a `_clear_logo.hex` which clears logo data from `0x800F800` address including `AA55F00D` indicator bytes.

I wanted to make HEX files that modify only these 4 bytes, but it does not work for me:

- `_enable_logo.hex`
```
:020000040800F2
:04F8000055AA0DF008
:00000001FF
```

- `_disable_logo.hex`
```
:020000040800F2
:04F800000000000004
:00000001FF
```

This would allow to keep current logo in memory and just disable it. Later to enable it again (possibly with nice abstract art, if no logo has been flashed before).

I noticed a comment in code:
`16 bytes is the only format the DFU seems to support`

OK so I tried to erase 16 bytes (overriding part of the logo), but it does not work either:
```
:020000040800F2
:04F80000000000000000000000000004
:00000001FF
```

I also tried several other options but no luck. Any insights? Is it really because of DFU or do I make something wrong?

**Comment by Ralim** [comment]
Hey,
The other thing with the files is that they must be over a certain length for it to accept them. This is why if you look at the logo files they repeat their contents, this is purely to bloat up the actual file size. Even though the DFU code seems to only program the flash once it just needs the bugger file size.
