### ISSUE TITLE
Issues with heating

### ISSUE THREAD

**Issue by Chosaint** [Ralim/ts100#199]
When I press the button closest to the iron tip to heat up, the display shows for a second then it shuts off, restarts, and back at the main menu where I can press the two buttons for settings or heating. I have tried several different firmwares to no success. Anyone else have this issue?

**Comment by Ralim** [comment]
Hi,
The first suspect when this occurs is the power supply that you are running the iron off, or a hardware problem. 

What power supply are you using?

**Comment by Chosaint** [comment]
was just coming back to update everyone, it was the crappy power supply that came with the TS100, I used the one that I use for my laptop and its working perfectly, same voltage rating as the crap one they sent, 19v
