### ISSUE TITLE
Menu locks up - whole device is unresponsive after a couple of seconds.

### ISSUE THREAD

**Issue by edmanning555** [Ralim/ts100#202]
As above - device stops responding after a few seconds, after a while the screen flashes and it works again for couple of seconds. Rinse and repeat!

I've tried using different firmware with the TS100 and they work fine. Is there anything I can do to help diagnose this issue?

**Comment by Ralim** [comment]
Hi,
Can you provide any further information to try and diagnose this?
Is there any particular menu prompt it happens on?
Does it happen when in the soldering menu?
Does it happen on the idle screen?

Can you try an few times and note when it happens?

Sadly I can't diagnose without more information :)

**Comment by edmanning555** [comment]
To answer your questions:

It happens in any instance regardless of menu, buttons pressed, or whether it is connected via USB or DC power brick, or any other state as far as I can tell.

It happens every time, there is not a single instance where the device functions correctly for an extended period of time.

**Comment by freeman0869** [comment]
So did the same thing for me last night, Bricked my TS100 after upgrading with .hex file...no response what ever you do, after you plug power or usb wire back in, it works for 2 seconds and no response after that for at least a minute...total freeze of menu. The upload went fine and I did get .RDY after updating but no response from TS100 any more !

**Comment by Ralim** [comment]
Can you please specify which firmware files (language and version) that are having these issues?

In the mean time you can just use DFU mode to roll back to the previous version for now. 

If you use a language different to English, can you please try the English one as well to confirm if it is a language specific bug or general bug?

**Comment by edmanning555** [comment]
Hi,

I am currently using the previous version which is fine. I personally use
the English version and haven't tried any other. Would you like me to?

**Comment by freeman0869** [comment]
I used TS100_EN.hex latest version and the older version but nothing worked now I did try another file I found here and totaly lost it..now it says ("BL FLASH"....CONT?...CHK CRC...FC6227E8...Done!) and that is By pressing the button closest to the tip...now I can not see it when pluged to the computer on Win 10...even when pressing the buttons. Any clue ?

**Comment by MathisDELOGE** [comment]
I just received my ts100 and I have the same problem. I tried with all versions from 2.0 (those before do not even boot).
In any menu, whan i plug a power supply, the screen freeze after about 2 seconds.

**Comment by freeman0869** [comment]
I tried all the files here and nothing works the only ones that do work are the originals ! So if anybody having same problems flash either one and your TS100 will be back online !

[Version 2.12and 2.17.zip](https://github.com/Ralim/ts100/files/1653860/Version.2.12and.2.17.zip)

**Comment by MathisDELOGE** [comment]
Thank you for the originals, I did not find them.
I just tried it, it works !

**Comment by Ralim** [comment]
Can you please confirm where you have purchased your TS100 units from? And roughly when?

Are these all new units?

@freeman0869  you flashed the conversion firmware to replace your stock bootloader with the dfu-util model instead (Im assuming you took that firmware from the thread with the discussion on alternate bootloaders).

I have reconfirmed correct operation on all of the units I have access to and have not had any issues with the firmware locking up on these units.

What you are experiencing with the reset after a few seconds is the watchdog timing out.
The watchdog is there to catch errors where one of the threads in the scheduler locks up.

The most likely cause of this is an issue with the I2C communications locking up the peripheral if there are transient errors on the bus (as these have an exclusivity around them as its a shared bus).

Are your units new or is this error new? 

This is most likely yet another new manufacturing change that is causing issues. The original firmware does not actually use any of the hardware acceleration in the STM32 and instead bashes everything out using software which is why its performance can be sub-par in some instances.
This also means that because its software runs really slowly (comparatively) it is less likely to run into issues with the hardware.

**Comment by freeman0869** [comment]
Thank you for the explanation of the  TS100...which I bought in December and received last week on the 16 of Jan.
 https://www.tmart.com/TS100-65W-Temperature-Adjustment-Built-in-STM32-Chip-Digital-OLED-Programmable-Soldering-Iron-Set-TS-I-Black_p341108.html...it was the cheapest combo for me.

 It is working with version 2.17 for now, and tried win 10, win 7, and linux Ubuntu to upload the same .hex file (no Apple) and figured it is the new TS100 models that I received that is the problem.

And I am pretty sure when I first received it last week it did say ver 2.18 on my Iron but, I'm yet to find that version anywhere !!!

**Comment by MathisDELOGE** [comment]
For me it's the same, i bought the ts 100 un december and received last
week so it's à new unit..
(Thanks for the nice explanation ;) )

Le mar. 23 janv. 2018 à 00:42, freeman0869 <notifications@github.com> a
écrit :

**Comment by Ralim** [comment]
Yeah okay, this could be an issue with the newer units coming out.
I have also noticed a trend in some of the cheaper seller's units having more issues than some others.
Not sure why that is though :/

The firmware that came on your Iron is *not* this repository. This firmware has just eclipsed up to the numbers that the official firmware uses. [This](http://www.minidso.com/forum.php?mod=viewthread&tid=892&extra=page%3D1) is the location of the *official* firmware.

I'm not sure what is causing the lockups on your units to be honest, as hopefully the hardware is the same as the official and there are not clones yet.

When I next have time Ill try and get a better debug firmware up for you. But Its really odd that the newer models are having this issue.

**Comment by Boyeen** [comment]
If it's of any use, I just purchased a TS-100 ("updated", brown, with 2 tips and power supply) from Banggood... It came with v2.12 MiniDSO firmware installed.

I updated to the latest firmware (v2.02) from this site with zero problems. The iron works correctly and the menus all work smoothly. Perhaps there are  "clones" being sold under the MiniDSO brand...   

BTW, awesome job Ralim. I LOVE the tiny font Settings descriptions, totally readable, super professional.  Way to go :-)  Thanks for your efforts.

**Comment by electroplated** [comment]
I have this exact same issue - bought the iron ob ebay from the link (https://www.ebay.co.uk/itm/12-24V-Mini-65W-Programmable-TS100-Electric-Solder-Soldering-Iron-LCD-Digital-UK/253273635474?ssPageName=STRK%3AMEBIDX%3AIT&_trksid=p2057872.m2749.l2649) on the 17th Jan and it arrived today. Only the stock firmware works, every other version I've tried works fine for about 2-3 seconds after power is applied then the buttons become unresponsive until reboot. Iron also got so hot when I had the latest release installed the entire tip was glowing bright red!!

**Comment by Ralim** [comment]
Hi,
Can you try this firmware on your units?
I have slowed down the I2C bus by 50%.
I'm guessing this is the most likely code to be locking up to cause the hanging issue.
[TS100.hex.zip](https://github.com/Ralim/ts100/files/1666308/TS100.hex.zip)

**Comment by xPsIXx** [comment]
This might help a bit. I received a unit and the barrel plug connector broke first time i plugged it in. I claimed a second unit and when it arrived it would freeeze after a couple of seconds with Ralim's firmware, the first unit never did. I now had two units so i swapped the daughter board of the new TS100 with the old TS100 and it worked like a charm... Note the silkscreen quality.

It takes about 5 seconds to freeze.
Sorry Ralim, that firmware doesnt work either.
 
![p1250090](https://user-images.githubusercontent.com/7002012/35426519-157ce650-027d-11e8-94cf-fc4970717c45.JPG)
![p1250091](https://user-images.githubusercontent.com/7002012/35426520-15b0774a-027d-11e8-9534-b02f3b0c3fc8.JPG)

**Comment by freeman0869** [comment]
You slowed down the software and it gives me 3 seconds more to surf the menu so 5 seconds in all until it freezes ! Sorry that software still doesn't work !

**Comment by Ralim** [comment]
@xPsIXx thank you! That confirms my fears that there has been a design change to the hardware.

Any chance you can get some high resolution photos of the front and back of the board that doesnt work?
Also if you can get the part number on the same square chip if it's changed compared to the other one :)

I'm guessing there is a redesign and something has changed subtly. 

Sorry about the new firmware not working yet, didnt know at the time that there was a hardware change.

**Comment by jonnieZG** [comment]
I would say from the photo that they just changed the layout of the components, so the control pins must have changed. We just have to figure which ones.

**Comment by electroplated** [comment]
Here's a quick video showing the behaviour with the firmware you posted up to try

https://www.youtube.com/watch?v=vCduzDBHiVQ&feature=youtu.be

As you can see it not only locks up but also starts heating up without updating the temperature readout which can lead to burnt fingers or worse perhaps?!

Here's a shot of the chip inside
<img width="539" alt="screen shot 2018-01-26 at 17 37 34" src="https://user-images.githubusercontent.com/6450685/35452801-c4d0ee84-02bf-11e8-851e-649dce179de3.png">

Let me know if there's any other info, photos or tests I can do to help :)

**Comment by xPsIXx** [comment]
freeman0869 indeed has the same board rev. 
For completion sake, better quality pictures.

![p1270108](https://user-images.githubusercontent.com/7002012/35472126-a30471a4-0382-11e8-9f5e-48603b088448.JPG)
![p1270109](https://user-images.githubusercontent.com/7002012/35472102-5f963434-0382-11e8-8abc-6b48bfa39756.JPG)
![p1270107](https://user-images.githubusercontent.com/7002012/35472103-5fc3bada-0382-11e8-95ed-5fe8b4320d1a.JPG)

**Comment by xbeefpv** [comment]
Hi Ralim! i have the same problem, the TS100 freezes. My product is this:
https://www.getfpv.com/ts100-digital-oled-programmable-interface-mini-soldering-iron.html

Did you have a solution? Thanks!

**Comment by Ralim** [comment]
Hi,
It appears that either there is a second revision of the mainboard out there or someone has changed something in these units.

As not all units are affected, I'm not sure if it's an old/new stock issue or some other manufacturer out there.

What would be ideal, is if someone who has one of these units could use a multimeter with a fine point tip and trace out the connections from the sides of the STM32 to the bottom connector.

I'm also going to try and make an I2C probe firmware to check if the accelerometer has been changed in this version.

**Comment by freeman0869** [comment]
I've been using the Iron a lot and the accelerometer does not seem to work I set my time out at 600 and when I pick it up after not using it in between soldering it seems to not wake up even if I shake it a lot...so I constantly have to repress the button close to the tip to restart the iron !

**Comment by Ralim** [comment]
Interesting, which firmware are you running ?

**Comment by xbeefpv** [comment]
im trying with many, 2.0 2.2
but only the original firmware works fine.
Strange, but untill the oldest firmware not working. thanks for your reply @Ralim

**Comment by SquiglyD** [comment]
Same issues here, purchased last week from getfpv, when I first received the iron I noticed it had firmware v2.18 (cant seem to find this anywhere) after trying yours I reverted back to V2.17. Just tested to see if the ACC is working and it appears not, torch will only come out of sleep mode by pressing the front button, motion has no effect.

**Comment by electroplated** [comment]
Ralim - I've just tried to trace out the connections between the STM32 and the 16 pin connector on the opposite side of the board. I managed the first 8 pins ok but the second set were almost impossible to check reliably with the tools I have to hand right now - I have fine tips on my multimeter but its; still very tricky without an extra pair of hands!

As best I can tell, the first 8 connectors are connected as follows, using the attached images for reference.

1 - 29
2 - 30
3 - 32
4 - 33 & 34?
5 - 33 & 34?
6 - 32
7 - 6
8 - 7

<img width="974" alt="connector" src="https://user-images.githubusercontent.com/6450685/35761262-94ac5a62-087e-11e8-91af-cc70875d0697.png">
<img width="652" alt="stm32" src="https://user-images.githubusercontent.com/6450685/35761263-94c83d7c-087e-11e8-8ad2-3204c817b935.png">

I'll try and double check these and do the other 8 tomorrow if I can find a better way of doing such small scale work without better magnification!

**Comment by 1upRacing** [comment]
Ralim - If you are unable to get this sorted out I can send you an iron that has the issue.  Just received an order of 5 that won't work with your firmware upgrade.  

You're welcome to keep it afterwards to work on future upgrades.  Just get in touch if you need.

**Comment by alexanderkozhinov** [comment]
Ralim, same to me. New device from Ali with 2.18, DFU: 3.43
Freeze after 2 seconds > 2.17 > ACC doesn't work.

**Comment by sascha108** [comment]
Hi Ralim,
same problem, ts100 from banggood with 2.17
pcb is same as freeman0869

**Comment by Ralim** [comment]
@1upRacing Where in the world are you located?
I'm tempted to take you up on this offer, however, I would like to make up an I2C tester firmware first.

@sascha108 @alexanderkozhinov 
Can you confirm if the accelerometer function works for you in the original firmware?

**Comment by 1upRacing** [comment]
I'm in the US but do a lot of international shipping so it wouldn't be any inconvenience to send one of these out to you.

**Comment by Ralim** [comment]
@1upRacing Would be wonderful if you could.
Just hit me up on ralim@ralimtek.com to discuss.

**Comment by alexanderkozhinov** [comment]
@Ralim on 2.17 at the moment TS100 doesn't react on shake in sleep. I need to push button to wake it up.
I didn't tested if it will go to sleep even in use (in motion).

**Comment by SilverSho0t** [comment]
They maybe removed the accelerometer on new ones.

**Comment by Ralim** [comment]
I don't think so, there is still an ic on the board, but I'm wondering if the model has changed and I just need to write a new driver for it (hopefully).

They may have changed the pinout as well subtly so ill be checking it as well :)

Mostly just need time :(

**Comment by sascha108** [comment]
Hi Ralim,
there are no function with accelerometer @V2.17, TS100 go's to sleep no matter its moved or not.

**Comment by kormyen** [comment]
@Ralim I just got a new TS100 from [Ali](https://www.aliexpress.com/item/1pc-Free-Shipping-Brand-New-1-Set-Mini-Portable-65W-Programmable-TS100-Electric-Soldering-Iron-Digital/32689219813.html) with the same 2-3 second freeze with your hex. Works fine on stock 2.12 and 2.17. Happy to help or test anything if you explain steps. Cheers!

**Comment by Ralim** [comment]
Hi,
This definitely looks like a new batch of the units coming out. 

@1upracing has offered to send an affected unit to me, so when I pick up that one I will aim to get this up and running asap after that.

Not sure on an exact date sadly, but will let you all know :)

Sorry for the delay :(

**Comment by kormyen** [comment]
Sweet. Good luck! :D

**Comment by undirezt** [comment]
Hello. I also ran into this problem. The differences are not only in the PCB, but also in the absence of the stub hole for the sting and the other side of the packaging.
But, I still have not figured out, is this change in the original design or began to produce a fake?

**Comment by AcidBurns** [comment]
![img_20180216_000653](https://user-images.githubusercontent.com/3296309/36287089-0ef3d582-12b3-11e8-8cf2-9a4cd0fff253.jpg)
![img_20180216_000630](https://user-images.githubusercontent.com/3296309/36287090-0f0d9b3e-12b3-11e8-9eb1-e6b254a99719.jpg)
![img_20180216_000541](https://user-images.githubusercontent.com/3296309/36287091-0f257286-12b3-11e8-99de-6090c9aa08aa.jpg)
![img_20180216_000505](https://user-images.githubusercontent.com/3296309/36287092-0f3ec22c-12b3-11e8-817f-08a41b246bdd.jpg)
![img_20180216_000420](https://user-images.githubusercontent.com/3296309/36287093-0f5785c8-12b3-11e8-853f-cc874cd8e03e.jpg)
![img_20180216_000351](https://user-images.githubusercontent.com/3296309/36287094-0f7178d4-12b3-11e8-9ef6-70855a0d078f.jpg)
I also made some pictures, high res with my magnification camera. I hope it helps. Needless to say that I got the same problem :D

**Comment by TomK** [comment]
Same issue here, using 2.02.
My brand new TS100 received a few days ago locks up after a few seconds. The same firmware works fine on an older TS100.

**Comment by Ralim** [comment]
Hi,
As a quick check, could someone please run this firmware and tell me the two numbers it prints out on your non-working unit ?
[TS100.zip](https://github.com/Ralim/ts100/files/1734510/TS100.zip)

**Comment by kormyen** [comment]
025 060

**Comment by TomK** [comment]
same here - 025 060
![mvimg_20180218_080451](https://user-images.githubusercontent.com/299656/36349617-bf49b958-1482-11e8-9509-e4b1f6facf03.jpg)

**Comment by Ralim** [comment]
Thank you both.
This confirms that the accelerometer in your units is definitely a totally different unit.
Can you also try this firmware please :) (Sorry about this)
This tries to read the device ID register from the 3 most common accelerometers with that device ID.

Hopefully one of these matches up, if not I will definitely have to wait for the unit in the post to me to arrive. If one lines up Ill try and start working on a library for the new accelerometer and test once the unit on the way to me arrives.

Sorry about this :/
[TS100.zip](https://github.com/Ralim/ts100/files/1734558/TS100.zip)

**Comment by TomK** [comment]
It's not a problem, your work is much appreciated!
000-013-015.  :)

![mvimg_20180218_095224](https://user-images.githubusercontent.com/299656/36350538-973daa50-1491-11e8-8b74-c78a04d1e9a4.jpg)

**Comment by kormyen** [comment]
@Ralim 
Happy to help. No worries at all to test further.
Same here with the 2nd zip.
000-013-015.

![20180218_235514](https://user-images.githubusercontent.com/836507/36351006-59599b60-1507-11e8-8846-0135b948978a.jpg)

**Comment by AcidBurns** [comment]
for me it's also 000-013-015.
those chinese guys, simply changing hardware without notice 👎

**Comment by Ralim** [comment]
Bummer, those dont match any of the common ones :(
I'll hopefully be back soon with more information when the next one turns up (Or if i find more likely candidates to test)

**Comment by xavkno** [comment]
Wouldn't it be easier to change out the component for the one on the previous hardware version?

**Comment by badm1n** [comment]
2nd zip. Bought from Banggood on 2018-01-29.
![ts100](https://user-images.githubusercontent.com/4036630/36352971-dbdb773c-14c8-11e8-9247-deaedd6315d9.jpg)

**Comment by Ralim** [comment]
Hi,
Sorry for the delay in response. I have been spending the last two days trying to figure out what make that damn IC is and haven't gotten very far. I have also reached out to miniware to see if they will help.

In the meantime, the below firmware will work but it disables sleep mode as it just doesnt talk to the accelerometer. This will still provide all the rest of the firmware for you hopefully until we can identify this ic.

[TS100.zip](https://github.com/Ralim/ts100/files/1755701/TS100.zip)

**Comment by bubblefish12** [comment]
Yes, it works

**Comment by sascha108** [comment]
It works fine - in original V2.17 its always go sleep after max sleeptime :(
I hope that you can identify the chip soon.

**Comment by xbeefpv** [comment]
Works good! thanks Ralim! nice Work! i will be awaiting for the the complete functions

**Comment by electroplated** [comment]
Also working fine for me - amazing job! 

Can anyone else confirm if it's normal at any temperature for the tip of the iron to glow bright red?!
With the older non compatible firmware loaded my iron got that hot which I've never seen an iron do before, just repeating that aspect here for anyone who might inadvertantly try the older firmware on one of these irons.

**Comment by TomK** [comment]
From what I gather, if it crashes while it's heating, it will continue to heat indefinitely until it burns out.

**Comment by adrien3d** [comment]
@electroplated @TomK Indeed, with the v2 and v2.02 firmwares (and I guess all previous firmwares too), the firmware bugged and heated the tip indefinitely, so it was a glow bright red.

**Comment by badm1n** [comment]
I reconstructed the datamatrix from the new accelerometer chip and it reads **2701409731410788** but sadly I didn't get any matches from Google.

![accelerometer_datamatrix_1](https://user-images.githubusercontent.com/4036630/36678634-f16f1930-1b19-11e8-9ec0-d1d554e73dce.png)
![accelerometer_datamatrix_2](https://user-images.githubusercontent.com/4036630/36678637-f3720a62-1b19-11e8-88d3-90e93f59a69a.png)

**Comment by sascha108** [comment]
@badm1n,
i tried the same and also with shorter substrings from this but i found nothing. I do not think it is the chip name.

**Comment by adrien3d** [comment]
If @AcidBurns could make a magnified Hi-Res pic of the Accelerometer, it could help, but I guess from the font of the text above the QR code that it is a Bosch or ST accelerometer (not sure at all).

**Comment by Ralim** [comment]
The accelerometer has been identified as a Lis2dh from ST.
I'm currently writing the driver code now for this unit 😄 
Just working on orientation detection and some more tests and then I should have another firmware to push out.

**Comment by Trezona** [comment]
Ben does this mean that from now on you will have to have 2 separate versions of your software?

**Comment by Ralim** [comment]
Nope,
Adding auto-detection on startup so should be transparent to the user.

Just give me a bit more time and Ill get something out for you :)

**Comment by Trezona** [comment]
Ahh, ok, clever! :-)

**Comment by xbeefpv** [comment]
Thanks RALIM!

**Comment by magyarl89** [comment]
The same issue here!
Ordered on [Gearbest](https://www.gearbest.com/boards-shields/pp_266258.html), on 5th of Febr.
Your hotfix without accelerometer works great!
We are looking forward for the update, keep on that great work! Thanks very much!

**Comment by assasinmaxy** [comment]
@Ralim Hello! I'm from Russia and I also received such a copy of the soldering iron. I'll be glad to help than I can.

**Comment by Ralim** [comment]
Okay,
*Hopefully*, this version should work, but naturally whenever I push firmware someone always finds a bug.
I've tried to setup the sensitivity to be fairly similar to the old hardware so should be okay.
[TS100.zip](https://github.com/Ralim/ts100/files/1770925/TS100.zip)

Would love feedback on sensitivity etc :)

**Comment by assasinmaxy** [comment]
@Ralim Quite sensitive happened. But at the sensitivity level 1, the soldering iron has problems with falling asleep. For some strange reason, the time to go to sleep can exceed the set time. Instead of 30 seconds, I measured in order: 47, 60, 67, 78 (here I did a reboot), for 180 seconds and did not fall asleep, I ported it and for 120 seconds he did not fall asleep again. I reloaded the soldering iron, and he fell asleep in 60 seconds, then after awakening he again fell asleep in 60 seconds. Next, I set the threshold for falling asleep 10 seconds. The first time the dream came in 40 seconds, the second time he did not fall asleep even after 100 seconds. Next, I set the sensitivity to 9 and he fell asleep in 22 seconds, then through 20, 21, 16, 14, 22. Measurements I spent while the soldering iron was lying on the table. I did not shake the table. Also at the sensitivity level 9, the soldering iron can sometimes be easily awakened, and sometimes it is necessary to shake. And he very often wakes up himself. After these observations, I set the sensitivity level 2. The soldering iron did not wake up if you gently move it on the table when it sleeps. But it's worth poking it carefully, as he immediately wakes up. In sensitivity mode 2, the device goes to sleep after 20 seconds or more. Also in mode 2 he wakes up.
In general, summing up, there is a feeling that the sensitivity threshold is not adjusted at all (sorry if these words offend you, I know you tried), the soldering iron can fall asleep much later than necessary. Still can itself to wake up.

**Comment by assasinmaxy** [comment]
@Ralim Does the position in space affect the readings? The fact is that when I was engaged in the module MPU6050 (gyroscope + accelerometer + thermometer), the readings of the Z axis accelerometer in the horizontal position could vary from -180 degrees to +180 at rest. In general, I will conduct more experiments, approximately to real conditions and record a video.

**Comment by assasinmaxy** [comment]
Here is link with video [https://yadi.sk/i/Vn-EDRtG3SuSZK](url)

**Comment by boklubre** [comment]
I have a problem with the newest Firmware.
Wake up with shaking works but the orietation of the Screen changed (fliped 180°).

**Comment by SquiglyD** [comment]
Big thumbs up from my side, it goes to sleep when left alone and wakes when picked up, thanks @Ralim for all the efforts as always!!

**Comment by simicblu** [comment]
@Ralim you sir are a god, I've just received my TS100 (from ebay generic seller), and it is one of the newer models. I can not tell you how grateful I'm because you made the firmware in the first place, but I'm even more grateful to you and all other people that helped you diagnose and resolve the problem.

Once more I just wanted to give you all an enormous thank you!

P.S. I've uploaded some firmware file firstly trough my apple machine, and I thought that that was the issue, but after following up on my windows machine this whole thread I've decided to upload some of the latest .hex files via my apple machine and they're working 100%normally. My apple config is mac mini late 2014, running high sierra. On the other hand motion sensitivity, in my personal opinion, is set to 1 and is normal (maybe when I gather some more experience I could provide with a more adequate feedback) Menu doesn't freeze any more, everything works like a charm.

**Comment by freeman0869** [comment]
Wow that's the good one @Ralim works a charm, everything is OK from my part nothing to complain !
Thanks a lot, very appreciated !!!!

**Comment by Ralim** [comment]
Thanks for all your comments!
@boklubre the screen will change orientation automatically depending on how you hold it in your hand, this can be disabled in settings. 

@assasinmaxy the timing issue is known, and I'm working on a fix for that now which is just being tested a but more. Thank you for the feedback on the sensitivity, I'm still tweaking it, just the two units respond differently so need to get them feeling the same :)
I'll try and get another version up soon with improved sensitivity controls

**Comment by xbeefpv** [comment]
Ralim, your work it's awesome! all of features on my TS100 it's now WORK!

thanks very much!!

**Comment by assasinmaxy** [comment]
@Ralim спасибо, ваша работа высоко ценится здесь! Очевидно что скоро данная тема станет очень популярной.

**Comment by Ralim** [comment]
Ill try and re-adjust the accelerometer sensitivity and then ill push out an alpha to let this be more known :)

**Comment by Ralim** [comment]
This was closed automatically by the merge, please ping back when you have issues :)
Happy to re-open if we run into more issues.
The new alpha release includes all of these changes, and also fixes the timing issues and should make the sensitivity much more similar hopefully.

😄

**Comment by xalius** [comment]
I have also received a TS100 with the new version of MCU PCB. The accelerometer seems to work fine when powered from USB, I can use the menu and the display flips when I turn the TS100 upside down, but if I connect a DC power supply the firmware seems to lock up during startup and the tip is heated indefinitely...

**Comment by jeckel2788** [comment]
i am having the same problem that alot of people are stuck in dfu after trying to update. i tried alot of different things. maby if i used a diff program/driver than windows it may help. getting no disk and errors alot. alot of people are bricking there unit , you can go back to the stock firmware, which i did until this gets worked out. here its a link. download the zip file. 

http://www.minidso.com/forum.php?mod=viewthread&tid=892

**Comment by huynhdesign** [comment]
> I tried all the files here and nothing works the only ones that do work are the originals ! So if anybody having same problems flash either one and your TS100 will be back online ! If for any reason you can't see your TS100 use this link...https://devanlai.github.io/webdfu/dfu-util/ and you can recuperate by uploading a " *.bin "file to your iron. to get your DFU 3.43 back.
> 
> [Version 2.12and 2.17.zip](https://github.com/Ralim/ts100/files/1653860/Version.2.12and.2.17.zip)
> [Ts100.bin.zip](https://github.com/Ralim/ts100/files/1653879/Ts100.bin.zip)

Hello! My ts100 is like you BLFALASH. and I follow this instruction to upload the .bin file, the screen is not displayed. I uploaded the file ts100-stockbl.bin and the screen shows BLFLASH. Please help me
Link video: https://youtu.be/134pZ6Hqal4

**Comment by huynhdesign** [comment]
I cannot get back DFU 3.43

**Comment by Ralim** [comment]
@huynhdesign 
If you use the web tool to upload the stock boot loader back. You will then need to reboot normally and press the A key to confirm. (Same process as you used to put the alternate boot loader on the device in the first place).

After this is performed, rebooting  while holding the A key should put you back onto DFU 3.43 as before you started this.
