### ISSUE TITLE
"Exponential" change of menu/options

### ISSUE THREAD

**Issue by SilentException** [Ralim/ts100#205]
While adjusting (for example) shutdown time you can hold the tip button and the option will increase slowly in linear fashion. It would be nice if the value change would be faster and faster (up to a limit) the longer you're holding the button. This is quite common behavior in menu systems of this kind. Thanks!

**Comment by Ralim** [comment]
Yes,
I agree that this would be a nice feature to have!

**Comment by jonnieZG** [comment]
Implemented here #238

**Comment by SilentException** [comment]
Just got around testing this. Wonderful feature :) Thanks @jonnieZG and @Ralim !
