### ISSUE TITLE
lower sleep time

### ISSUE THREAD

**Issue by tcurdt** [Ralim/ts100#209]
I would love it if the minimum sleep time could be lower than 1 minute.
Given it's heating up so quickly I think 30s would be good.

And thanks for the awesome firmware.

**Comment by Ralim** [comment]
Hi,
The sleep timer goes down to 10 seconds?
Just keep pushing the button and it wraps around to lower figures after 10 minutes :)

**Comment by tcurdt** [comment]
Doh! Perfect.
I Guess it was too late when I was trying :)
Thanks. Sorry for the noise.
