### ISSUE TITLE
Reset when working temp reached

### ISSUE THREAD

**Issue by NegativCut** [Ralim/ts100#210]
Hi, my TS100 resets when it reaches 260 C working temp. I have tried it at various temps with the same results. Power Supply is 19V @ 3.42A and I notice the LED on the PSU dims when the reset occurs.
Firmware is 2.17.
[CONFIG.TXT](https://github.com/Ralim/ts100/files/1740187/CONFIG.TXT)

**Comment by NegativCut** [comment]
Stand down, changed to a Sony 19V 3.3A and the TS100 now works perfectly.

**Comment by Ralim** [comment]
All good.
Almost all issues with resets are power supply related :)
