### ISSUE TITLE
Power indicator missing

### ISSUE THREAD

**Issue by DragonHunter274** [Ralim/ts100#211]
after the update the power indicator was missing

**Comment by Ralim** [comment]
Hi,
Can you please provide more details?

**Comment by Ralim** [comment]
Can you please clarify if this is an issue with the battery indicator not showing up for you?
Or is there an issue with the power indication iron ?

**Comment by DragonHunter274** [comment]
it is the power indocator that shows the power the iron is using in a bar like in previous versions instead of the chevrons

**Comment by Ralim** [comment]
Hi,
The power bar from 1.x was removed in the 2.x series as it was poorly calibrated and didn't accurately reflect the power level going to the tip.

In the newest 2 alpha you can enable detailed soldering screens that will show the actual duty cycle that the tip pwm is implementing if you want.

Adding a power bar is a potential option, but it has been 6 months since it was removed with no one complaining and no one asking for any indication either, so it's probably not a massively asked for item?

**Comment by JohnEdwa** [comment]
@Ralim 

One way would be to split the 'whisps of smoke' into a bar graph:

Vertical : ![smoke_2](https://user-images.githubusercontent.com/5417183/38732874-96e09b8c-3f28-11e8-8191-81d11fa25ee3.png)

Complex/segmented: ![smoke_1](https://user-images.githubusercontent.com/5417183/38732964-e1c2de9e-3f28-11e8-97fa-dfa73bf9e07a.png)

While the segmented could have as many as 24 states if it's pixel by pixel, or 7 if it's divided by 'smoke segments' and is easier to read accurately, I personally feel the vertical to be better looking and much easier to implement as well - either clip the graphic, or just draw a black box on top of it.

Add in *tiny* bit of averaging, and you have power indicator to match the much-improved temperature you added in 2.04.

**Comment by Ashdinalt** [comment]
I don't think one really needs a power bar, but to have some animation to this icon would be nice

**Comment by Ralim** [comment]
@JohnEdwa I prefer the first option was it maps easier to 0-100% range for the PWM output.
Could you create a set of 12x16 (12 pixels wide) graphics for these ?

**Comment by JohnEdwa** [comment]
@Ralim 
Sure, but you could save some flash space if you implemented this by drawing a black box on top of the full graphic that hides the part of the smoke whisps that aren't needed.

Combined:
![combined](https://user-images.githubusercontent.com/5417183/38773894-fc821a7c-4060-11e8-8114-b9933b08fe12.png)
![iconbined](https://user-images.githubusercontent.com/5417183/38773896-fd7f3a22-4060-11e8-8057-980ef2bbabd9.png)


Separate files:
![1](https://user-images.githubusercontent.com/5417183/38773854-69e8b040-4060-11e8-874e-d912d4efaf76.png) ![2](https://user-images.githubusercontent.com/5417183/38773855-6a08b584-4060-11e8-8f1d-c81a081ff2ac.png) ![3](https://user-images.githubusercontent.com/5417183/38773856-6a2760d8-4060-11e8-8c30-8c4f5c1eb6fc.png) ![4](https://user-images.githubusercontent.com/5417183/38773857-6a45d004-4060-11e8-8b23-45f80018f926.png) ![5](https://user-images.githubusercontent.com/5417183/38773858-6a641e06-4060-11e8-83ef-fb3d6aca7b59.png) ![6](https://user-images.githubusercontent.com/5417183/38773860-6a844e92-4060-11e8-8aa3-edcc818dc801.png) ![7](https://user-images.githubusercontent.com/5417183/38773861-6aadd7da-4060-11e8-9a7a-e7a0ea3a6dbe.png) ![8](https://user-images.githubusercontent.com/5417183/38773863-6acbf60c-4060-11e8-9a9d-db614da3c25f.png) ![9](https://user-images.githubusercontent.com/5417183/38773865-6ae79b28-4060-11e8-9fd5-49f71db260ea.png)
![i1](https://user-images.githubusercontent.com/5417183/38773871-7a1a9d16-4060-11e8-9c17-b8ecb60308d2.png) ![i2](https://user-images.githubusercontent.com/5417183/38773872-7a3936e0-4060-11e8-987e-c6dfa15c1ef1.png) ![i3](https://user-images.githubusercontent.com/5417183/38773873-7a5737e4-4060-11e8-806d-dcf1bc8fb0e4.png) ![i4](https://user-images.githubusercontent.com/5417183/38773874-7a744fe6-4060-11e8-9b7d-04daa842783c.png) ![i5](https://user-images.githubusercontent.com/5417183/38773875-7a948f7c-4060-11e8-8961-cd0bdc4dfde8.png) ![i6](https://user-images.githubusercontent.com/5417183/38773876-7ab27d34-4060-11e8-9d9c-a97d2b5c12b2.png) ![i7](https://user-images.githubusercontent.com/5417183/38773877-7acfc466-4060-11e8-9f19-6d36bf50fbc3.png) ![i8](https://user-images.githubusercontent.com/5417183/38773878-7aee2e88-4060-11e8-95a4-23f5d8c19261.png) ![i9](https://user-images.githubusercontent.com/5417183/38773870-79fa9b38-4060-11e8-8a0c-6862ddcdd988.png)

**Comment by Ralim** [comment]
Confirming I did implement this with drawing over in the end :)
