### ISSUE TITLE
Device stops heating sometimes(TM)

### ISSUE THREAD

**Issue by fiechr** [Ralim/ts100#212]
This may be not software related, but I still wanted to ask if maybe someone has any idea.

Since updating to the latest version the iron sometimes stops heating and the blink screen (which I enabled) is showing. It's like pressing both buttons simultaneously, except I didn't. Sometimes this happens twice in a few minutes, and then again it's working fine for over an hour.

Maybe the power supply (19V, 3,16A, HP laptop supply)? Is there a way to check if the device resets or "thinks" buttons were pressed or something like that (debug mode?)?

EDIT: It did reset to factory defaults, but the issue remained.

**Comment by Ralim** [comment]
It is quite possible that a power supply issue is causing the unit to reset back.
Also remember that long holding the rear (usb end) button will exit as well, so if you are using the boost function its possible to slip on your grip and hold the wrong button ?

At the moment there is no real good way to check, any suggestions ?
