### ISSUE TITLE
Changing Display Orientation A -> R/L requires a power cycle to apply if done with the wrong orientation.

### ISSUE THREAD

**Issue by JohnEdwa** [Ralim/ts100#231]
* **I'm submitting a ...**
  - [x] Bug report

* **What is the current behavior?**
Changing 'Display Orientation' from R/L to A enables the autorotation, but swapping from A to L or R while in the opposite orientation locks the wrong orientation until a reboot.

* **What is the expected behavior?**
Rotate the screen to the set orientation when the user changes the setting, even if it is 'upside down'.

***Steps to reproduce:***

1. Display Orientation set to A, rotate iron so tip points right (L rotation)
2. Set Display Orientation to R.
3. Screen is now stuck to the 'L' rotation until reboot no matter how you rotate the iron.

* **What are you running:**

  - Firmware Version: 2.03 MAR 14 2018 (RC2)
  - PCB Version: 1

**Comment by Ralim** [comment]
Fixed locally, will push up to to github when im back online shortly. Thanks for this.
