### ISSUE TITLE
Translation string length?

### ISSUE THREAD

**Issue by The-M1k3y** [Ralim/ts100#233]
- [X] Question

Hi, I really like your Firmware and am working on the german translation at the moment and ran into something I did not understand.

For some texts (like UndervoltageString) there is a comment with the length of the strings. Are those mandatory values? Some comments are "Must be <= x" and some only "<=". Some clarification would help.

**Comment by jonnieZG** [comment]
It's the same, and means that the text length **must** be less or equal than the specified number.

**Comment by The-M1k3y** [comment]
ok, thanks for the clarification.

**Comment by The-M1k3y** [comment]
ok, I missed something. Is there a limit on SolderingAdvancedPowerPrompt" ?

**Comment by Mrkvozrout** [comment]
@The-M1k3y hi, length of that string is <= 12

Max chars on display for big font is 8, for small font is 16. Here the value takes 3 digits plus percentage sign so 16 - 3 - 1 = 12 ;)
