### ISSUE TITLE
bug 2.03cr2

### ISSUE THREAD

**Issue by SmayK** [Ralim/ts100#235]
Please edit this template and fill out all the information you can (where relevant). Failure to provide essential information can delay the response you receive.

* **I'm submitting a ...**
  - [x] Bug report
  - [ ] Feature request
  - [ ] Translation

* **Do you want to request a *feature* or report a *bug*?**
hello I come to test version 2.03cr2, I have a problem with the ignition the temperature rises to more than 500 and this place out of service. the official version "2017.5.12 Update: TS100 APP 2.17" no problem

firmware
 TS100_FR.hex

**Comment by SmayK** [comment]
again, then after reinstalling the official version tests and reinstalling the 2.03cr2 the bug is gone. may be due to the basic management of the fireware provided with the purchase. the update of the latest version of the official followed by yours has worked properly. test to do maybe.

**Comment by federck** [comment]
There is also an error in string 534: /* (<= 11) Display Help Text Scroll Speed     */ {"Description "," Vitesse de défilement"}.
The characters exceed the maximum number permitted.

**Comment by SmayK** [comment]
yes I have changed since. seeing I got the iron i saw the worry see my link

**Comment by federck** [comment]
Pardonne-moi :)

**Comment by SmayK** [comment]
pas de problème :)
