### ISSUE TITLE
Fluctuations at the time of the impulse to maintain the temperature.

### ISSUE THREAD

**Issue by fishingpro** [Ralim/ts100#263]
* **I'm submitting a ...**
  - [✔] Bug report

* **Do you want to request a *feature* or report a *bug*?**
Bug

* **What is the current behavior?**
The set value periodically increases greatly

* **What is the expected behavior?**
Expected to be stable significance or small throws 5-10 degrees

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

***Steps to reproduce:***

1. Advanced soldering screen  - enabled
2. Set tempirature 150 °C
3. Look
4. When the set value is reached, a jump of + 20-40 ° C occurs. After a short time, the temperature is stabilized and becomes 5-10 degrees more than it is set and gradually decreases.

***Video of problem if hard to reproduce***
https://www.youtube.com/watch?v=yt_rqbAsOTc

* **What are you running:**
  - Firmware Version: 2.03 Mar 31 2018
  - PCB Version: 2
  - Power Supply: 22.2V

* **Other information** 

The value of the throw is higher the lower the set temperature. The proposal in the first instants after the arrival of the stabilizing voltage does not measure the temperature, but reject the set value. This will avoid abnormal throws.

**Comment by Ralim** [comment]
Can you please use the issue template to break up your issue into the seperate headings to make it easier to answer / reference to when replying?
You have not provided some of the information asked for in the template.

**Comment by fishingpro** [comment]
description fixed

**Comment by Ralim** [comment]
Aha, thank you. Sorry to ask you to update this, but much easier to confirm this is the same issue as #261. :)

**Comment by fishingpro** [comment]
2 themes are created in 1 day. we can assume that the failure lies in the last update.

**Comment by Ralim** [comment]
Yeah, the timing on the(  PWM -> PWM ) <-> ADC linking was updated, but on different tips and different units these times can vary. Its a trade off because the tighter the timing the better the performance of the iron, but looser timings are more tolerant of the tip variations. The 2.03 works on all 8 irons I can get access to easily, with 16 tips between them. But there are always outliers.

**Comment by fishingpro** [comment]
it seems to me these emissions are associated with the imperfection of the tip. with instant power supply for some time there is an expansion of the heater and at this time there are problems with the measurement, after a while the spiral begins to show more predictably. just a small inductive effect is possible, the coil after all has some kind of inductance.

**Comment by Ralim** [comment]
This is less to do with the tip, and the recovery time of the entire system including the op-amp. It is a delay of around 4.5 - 5 milliseconds after the heat is turned off. So as of current the system waits for 5 milliseconds before measurement. I'm going to push this out slightly to see if it helps and upload a test firmware.

**Comment by fishingpro** [comment]
If you need pre-test testing, you can send me an assembly to an e-mail: x@x-id.ru

**Comment by Ralim** [comment]
[TS100.zip](https://github.com/Ralim/ts100/files/1882171/TS100.zip)

Hi, can you test to see if the above firmware improves the performance for you ?

**Comment by fishingpro** [comment]
It helped. The readings became more predictable, the upward shots lost anomalous indicators.

**Comment by Ralim** [comment]
Going to close this and just keep  #261
