### ISSUE TITLE
Text position when flipped

### ISSUE THREAD

**Issue by Nredor** [Ralim/ts100#27]
![screen_offset](https://user-images.githubusercontent.com/199049/28247302-55de64d8-6a36-11e7-8cae-c453a9735978.jpg)

Picture shows it all. Text position is bad when display is flipped.

**Comment by Ralim** [comment]
Woah that's not meant to happen.
I can't reproduce the issue on my Irons here, any chance you can tell me what version of the firmware you are on? Also, where did you buy your iron though?

Is it only on the soldering screen, or is it on all screens?

**Comment by Nredor** [comment]
Tried now with latest version. Ordered from https://www.banggood.com/MINI-TS100-Digital-OLED-Programable-Interface-DC-5525-Soldering-Iron-Station-Built-in-STM32-Chip-p-984214.html

Text is displayed fully but few pixels of the display are behind black mask. You see the whole text if you look from an angle.

**Comment by Nredor** [comment]
Ok, now that i look with bright light seems that my units display is not positioned correctly. So I probably have faulty unit ;) Software seems to be working as intended.

**Comment by Ralim** [comment]
It should be really easy to align the screen if this is just the issue. 
I might add a little bit more padding on the screen when I have time to test it too.
