### ISSUE TITLE
Bug: Unit randomly crashes / needs power off/on cycle

### ISSUE THREAD

**Issue by gamerpaddy** [Ralim/ts100#280]
## allready adressed in https://github.com/Ralim/ts100/issues/223
closed, i did use 2.03, now updated to 2.04

* **I'm submitting a Bug report** *

The Unit (TS100) randomly turns off and needs to be unplugged and plugged back in to work.
disabling shutdown (OFF) does not stop this from happening. button presses and shaking the unit does nothing.

* **What is the current behavior?**
display turns black at random, no reaction from button presses or shaking. unit cools down.

* **What is the expected behavior?**
unit keeps working as inteded with no random shutdown that cannot be turned back on without complete power cycle.

***Steps to reproduce (maybe):***

1. use it, happens randomly at random times mostly after 5-15min
it happened when heating up
it happened when in use
it happened when in standby 

***Video of problem if hard to reproduce***
hard to record, happens after 5..15min. sometimes even longer. 

* **What is the motivation / use case for changing the behavior?**
very frustrating to use if it turns off any moment

* **What are you running:**
it happens in any situation

  - german version
  - Firmware Version: 2.04
  - PCB Version: 2
april, 13, 2018
  - Power Supply (Voltage and Current Rating) :
laboratory linear power supply 30V / 7A. current limit set to 7A, using appropriate sized cables.

i tried running it at 19V.. 24V... 4S LiPo ...12V.  no difference
i tried strong shaking the unit  maybe a solderjoint is broken, but it didnt shut off.
same goes for cables and connections.

**Comment by gamerpaddy** [comment]
i tried recording it but after 20mins still no crash. obviously...
is there enough flash left to create logfiles in a debug build to narrow it further down?

**Comment by gamerpaddy** [comment]
allready adressed in a different reported bug regarding oled saver feature
https://github.com/Ralim/ts100/issues/223

**Comment by JohnEdwa** [comment]
It's not about the OLED. The TL;DR is that something from v2.03 that added support for the new accelerometer in PCB2 is causing the iron to freeze, but due to the way it's completely random on when it happens the cause hasn't been found yet.

From #279 :
> There is currently an ongoing investigation into the freezing problem in other issues, where it occurs easily on some units and really slowly on others. This appears to be memory allocation, and I just haven't had time to keep chasing it at this point in time. As you are using pcb 1, try the 2.02 and 2.03 releases.
-Ralim
