### ISSUE TITLE
Bug: back to main menu  also opens Version screen

### ISSUE THREAD

**Issue by gamerpaddy** [Ralim/ts100#281]
* **I'm submitting a ...**
  - [ X ] Bug report
  - [ ] Feature request
  - [ ] Translation

I found a bug regarding the Back button (near display) while in soldering mode.
when pressing it longer it should go back to the main / idle menu, but in 2.04 it rightaway opens the version menu, which can be left with a second button press.

* **What is the current behavior?**
when leaving soldering mode with back button, it  opens version menu which it did not in 2.03.

* **What is the expected behavior?**
should open main menu where version and settings menu can be accessed

***Steps to reproduce:***

1. be in soldering mode  
2. long press back button near display
3. version menu opens

* **What is the motivation / use case for changing the behavior?**
minor issue, just for quicker navigation.

* **What are you running:**
soldering mode

  - Firmware Version: 2.04
  - PCB Version: (2)
  - Power Supply (Voltage and Current Rating) : 24V (30V 7A regulated linear bench supply)

**Comment by Ralim** [comment]
This is already fixed in a commit and is just pending the next release build. #278
