### ISSUE TITLE
Cooldown blink doesn't activate

### ISSUE THREAD

**Issue by akrueger** [Ralim/ts100#289]
Please edit this template and fill out all the information you can (where relevant). Failure to provide essential information can delay the response you receive.

* **I'm submitting a ...**
  - [X] Bug report
  - [ ] Feature request
  - [ ] Translation

* **Do you want to request a *feature* or report a *bug*?**
Bug

* **What is the current behavior?**
No screen blinking on cooldown when option selected in settings

* **What is the expected behavior?**
Blinking screen on cooldown when option selected in settings

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

***Steps to reproduce:***
(cooldown blink option selected in settings)

1. Heat up iron
2. Exit soldering mode
3. Screen shows cooldown temp but no blinking is occurring.

***Video of problem if hard to reproduce***

* **What is the motivation / use case for changing the behavior?**

* **What are you running:**

On the idle screen, you can hold the settings button and it will show you the firmware version.

  - Firmware Version: 2.05
  - PCB Version: 2
  - Power Supply (Voltage and Current Rating) : 19V 2.1A

* **Other information** 

If submitting graphics to go on the iron, please use BMP or PNG files over JPG.

**Comment by Ralim** [comment]
Ah, this is because the original warning screen for tip temperature has been totally removed.
Ill add blinking to the new one. :)
