### ISSUE TITLE
Sleep and deep sleep do not always engage if user is left in the menu

### ISSUE THREAD

**Issue by GnFlala** [Ralim/ts100#293]
* **I'm submitting a ...**
  - [X] Bug report
  - [ ] Feature request
  - [ ] Translation

* **What is the current behavior?**
Sometimes when you are in the menu and let the solder iron alone while in the menu sleep and deep sleep do not activate.
It is more frequently seen if user changes a setting and let down the solder iron.

* **What is the expected behavior?**
Sleep and deep sleep to activate wherever you are, when user is not using the solder iron.
Maybe there should be a timeout of how much time the system stay in the menu after the last key press. Let's say 50 second. After that you will be kicked out of the menu.

***Steps to reproduce:***

1. Get in menu
2. Change an item with A button
3. Let the solder rest.

* **What is the motivation / use case for changing the behavior?**
Why should there be a timeout for kicking the user out of menu?
It is only the way I am used from other menu systems. Usually after x seconds they kick you out to the main screen.

* **What are you running:**

  - Firmware Version: 2.4.1
  - PCB Version: (2)
  - Power Supply (Voltage and Current Rating) : 14.5v 5A and 20V 20A

**Comment by Ralim** [comment]
This has been fixed in #532, and will be in the next release
