### ISSUE TITLE
HW differences?

### ISSUE THREAD

**Issue by Eldenroot** [Ralim/ts100#299]
I am sorry for opening a new issue, but my question is what is the hardware different between TS100 and "upgraded" TS100 version? If only color and the box it is fine, so this firmware will be compatible without any issue? Thank you very much, thus project is amazing!

**Comment by Ralim** [comment]
There is zero difference, just packaging.
There are two revisions that change the accelerometer, but this doesn't change functionality or performance.

This firmware will work on all versions :)

... 
Well all versions that are currently known

**Comment by Eldenroot** [comment]
Thank you, keep good work!
