### ISSUE TITLE
Improve soldering info screen

### ISSUE THREAD

**Issue by Ralim** [Ralim/ts100#3]
Need to make it look better, and possibly display input voltage or similar as well.

**Comment by CptZeroG** [comment]
Hi Ralim, 
I don't understand: have you implemented the display of input voltage? It would be very usefull :)

**Comment by Ralim** [comment]
Yes, 
It's under the Extras menu.
You can access it via the following steps:

1. On the idle screen press both buttons
2. The unit will now show the current tip temperature
3. Press the button near the tip of the soldering Iron
4. The unit will now show the input voltage that the Iron is measuring

For further information, there are some details in the readme on the main page of this repository.

**Comment by CptZeroG** [comment]
Ah ok, thanks Ralim, i did't found on the menu schema.

P.s. I hope that you add the custom logo feature...it's a great Fw :) complimets
