### ISSUE TITLE
Take fast average of temperature from power on.

### ISSUE THREAD

**Issue by dine909** [Ralim/ts100#308]
* **I'm submitting a ...**
  - [X] Bug report
  - [ ] Feature request
  - [ ] Translation

* **Do you want to request a *feature* or report a *bug*?**
bug

* **What is the current behaviour?**
Average temperature starts at 0 from power on, then spools up to the current ambient/set temperature - Unsure if the heating element will be switched in error due to this (i.e when average temperature is still spooling up and != actual temperature), I imagine it will if auto-start is enabled.

* **What is the expected behaviour?**
I would expect the current temperature to be sampled a few times to create a quick start point average to avoid confusion (as it looks like the iron is heating up)

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

***Steps to reproduce:***

1. Heat iron up to a temperature
2. Un-Power iron
3. re-power iron, observe temperature averaging up.

***Video of problem if hard to reproduce***

* **What is the motivation / use case for changing the behavior?**
To avoid confusion and make it easier to assess temperature instantly.

What are you running:

Firmware Version: 2.05
PCB Version: 2
Power Supply 18V lithium pack (5s) :

On the idle screen, you can hold the settings button and it will show you the firmware version.

  - Firmware Version: 2.x
  - PCB Version: (1/2)
  - Power Supply (Voltage and Current Rating) :

Video of problem if hard to reproduce
On request

**Comment by Ralim** [comment]
Can you confirm if this still persists in the 2.05 release for you?
