### ISSUE TITLE
PID behaves weird on ultra low tempearture

### ISSUE THREAD

**Issue by dogtopus** [Ralim/ts100#316]
Please edit this template and fill out all the information you can (where relevant). Failure to provide essential information can delay the response you receive.

* **I'm submitting a ...**
  - [X] Bug report
  - [ ] Feature request
  - [ ] Translation

* **Do you want to request a *feature* or report a *bug*?**

Report a bug

* **What is the current behavior?**

When set the iron temperature to 50 degC, the iron keeps slowly heating up until ~100 degC and bouncing around that temperature.

* **What is the expected behavior?**

The iron stays at 50 degC +- something resonable (not 50 degC).

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

***Steps to reproduce:***

1. Set the temperature to 50 degC
2. Put the iron into soldering mode
3. Watch the temperature bounce

* **What are you running:**

On the idle screen, you can hold the settings button and it will show you the firmware version.

  - Firmware Version: 2.05
  - PCB Version: 1
  - Power Supply (Voltage and Current Rating) : 19V 3.42A

**Comment by Ralim** [comment]
Hi,

Please see #275 & #309
