### ISSUE TITLE
V 2.04.01 no temperature unit in soldering mode

### ISSUE THREAD

**Issue by crosswind1964** [Ralim/ts100#319]
* **I'm submitting a ...**
  - [x ] Bug report
  - [ ] Feature request
  - [ ] Translation

  - Firmware Version: 2.04.01
  - PCB Version: (2)
  - Power Supply (Voltage and Current Rating) : 15 V

**Comment by Ralim** [comment]
Hi,
You are missing most of the information from the template.
I cannot fix perceived issues without information.

If this is about not showing C/F when you are soldering, this is as to be expected?
