### ISSUE TITLE
Serbian language

### ISSUE THREAD

**Issue by abrakatebra** [Ralim/ts100#329]
https://github.com/Ralim/ts100/blob/20d1874aee77c8ba9eb48f92546fe4ce5aab10a4/workspace/TS100/src/Translation.cpp#L1727

#ifdef LANG_SR
const char* SettingsDescriptions[17] = {
	// These are all the help text for all the settings.
	// No requirements on spacing or length.
	/* Power source (DC or batt)          */ "Izvor napajanja. Postavlja napon isključivanja. <DC 10V> <S 3.3V po ćeliji>",
	/* Sleep temperature                  */ "Temperatura na koju se spušta lemilica nakon određenog vremena mirovanja. <C/F>",
	/* Sleep timeout                      */ "Vreme mirovanja nakon koga lemilica spušta temperaturu. <Minute/Sekunde>",
	/* Shutdown timeout                   */ "Vreme mirovanja nakon koga će se lemilica ugasiti. <Minute>",
	/* Motion sensitivity level           */ "Osetljivost prepoznavanja pokreta. <0=Ugašeno, 1=Najmanje osetljivo, 9=Najosjetljivije>",
	/* Temperature in F and C             */ "Jedinica temperature. <C=Celzijus, F=Fahrenheit>",
	/* Advanced idle display mode enabled */ "Prikazivanje detaljnih informacija manjim fontom tokom čekanja.",
	/* Display rotation mode              */ "Orijentacija ekrana. <A=Automatski, L=Levoruki, D=Desnoruki>",
	/* Boost enabled                      */ "Držanjem prednjeg dugmeta prilikom lemljenja aktivira se pojačani (Boost) način.",
	/* Boost temperature                  */ "Temperatura u pojačanom (Boost) načinu.",
	/* Automatic start mode               */ "Ako je aktivno, lemilica po uključivanju napajanja odmah počinje grejati.",
	/* Cooldown blink                     */ "Blinkanje temperature prilikom hlađenja, ako je lemilica vruća.",
	/* Temperature calibration enter menu */ "Kalibrisanje temperature meri razliku temperatura vrha i drške, dok je lemilica hladna.",
	/* Settings reset command             */ "Vraćanje svih podešavanja na fabričke vrednosti.",
	/* Calibrate input voltage            */ "Kalibracija ulaznog napona. Podešavanje tastera, dugački pritisak za kraj.",
	/* Advanced soldering screen enabled  */ "Prikazivanje detaljnih informacija tokom lemljenja.",
	/* Description Scroll Speed           */ "Brzina kretanja dugačkih poruka <B=brzo, S=sporo>",
};

const char* SettingsCalibrationWarning = "Proverite da li je vrh ohlađen na sobnu temperaturu pre nego što nastavite!";
const char* SettingsResetWarning = "Jeste li sigurni da želite da vratite sva podešavanja na fabričke vrednosti?";
const char* UVLOWarningString = "BATERIJA";             // <=8 chars
const char* UndervoltageString = "PRENIZAK NAPON";      // <=16 chars
const char* InputVoltageString = "Napajanje: ";         // <=11 chars, preferably end with a space
const char* WarningTipTempString = "Temp vrha: ";       // <=12 chars, preferably end with a space
const char* BadTipString = "NEISPRAVAN VRH";            // <=8 chars
const char* SleepingSimpleString = "Zzz ";              // Must be <= 4 chars
const char* SleepingAdvancedString = "SPAVANJE...";     // <=16 chars
const char* WarningSimpleString = "VRUĆ";               // Must be <= 4 chars
const char* WarningAdvancedString = "OPREZ, VRUĆE!";    // <=16 chars
const char* SleepingTipAdvancedString = "Vrh: ";        // <=6 chars
const char* IdleTipString = "Vrh: ";                    // IdleTipString+IdleSetString <= 10
const char* IdleSetString = " / ";                      // preferably start with a space; IdleTipString+IdleSetString <= 10
const char* TipDisconnectedString = "VRH NIJE SPOJEN!"; // <=16 chars
const char* SolderingAdvancedPowerPrompt = "Snaga: ";   // <=12 chars
const char* OffString ="Off";                           // 3 chars max

const char SettingRightChar = 'D';
const char SettingLeftChar = 'L';
const char SettingAutoChar = 'A';

const char SettingFastChar = 'B';
const char SettingSlowChar = 'S';

const enum ShortNameType SettingsShortNameType = SHORT_NAME_DOUBLE_LINE;
const char* SettingsShortNames[17][2] = {
  /* (<= 11) Power source (DC or batt)          */ {"Izvor", "napajanja"},
  /* (<=  9) Sleep temperature                  */ {"Temp", "spavanja"},
  /* (<=  9) Sleep timeout                      */ {"Vreme", "spavanja"},
  /* (<= 10) Shutdown timeout                   */ {"Vreme", "gašenja"},
  /* (<= 13) Motion sensitivity level           */ {"Osetljivost", "pokreta"},
  /* (<= 13) Temperature in F and C             */ {"Jedinica", "temperature"},
  /* (<= 13) Advanced idle display mode enabled */ {"Detalji", "pri čekanju"},
  /* (<= 13) Display rotation mode              */ {"Rotacija", "ekrana"},
  /* (<= 13) Boost enabled                      */ {"Boost", "način"},
  /* (<=  9) Boost temperature                  */ {"Boost", "temp"},
  /* (<= 13) Automatic start mode               */ {"Auto", "start"},
  /* (<= 13) Cooldown blink                     */ {"Upozorenje", "pri hlađenju"},
  /* (<= 16) Temperature calibration enter menu */ {"Kalibracija", "temperature"},
  /* (<= 16) Settings reset command             */ {"Fabričke", "postavke"},
  /* (<= 16) Calibrate input voltage            */ {"Kalibracija", "napona napajanja"},
  /* (<= 13) Advanced soldering screen enabled  */ {"Detalji", "pri lemljenju"},
  /* (<= 11) Display Help Text Scroll Speed     */ {"Brzina","poruka"},
};
const char* SettingsMenuEntries[4] = {
/*Soldering Menu*/"Postavke\nlemljenja",
/* Power Saving Menu*/"Ušteda\nenergije",
/* UI Menu*/"Korisničke\opcije",
/* Advanced Menu*/"Napredne\nopcije", };
const char* SettingsMenuEntriesDescriptions[4] ={
"Postavke pri lemljenju",
"Postavke spavanja i štednje energije",
"Postavke korisničkih opcija",
"Upravljanje naprednim opcijama"
};
#endif

**Comment by CornyjK** [comment]
Please send this as pull request.
