### ISSUE TITLE
We need a release

### ISSUE THREAD

**Issue by jpis** [Ralim/ts100#336]
Hi Ralim,

The last release was on the 7th of May. 13 useful commit have been added since then. Please publish a new release so that we can enjoy them.

Thanks for all that you have done for the TS100 users community.

Best regards,

JPI

**Comment by NellyWhadsDev** [comment]
Any thoughts on this? Wondering if I should use the last release or wait for the next one if it'll just be a few days!

**Comment by Ralim** [comment]
@bakerenko 
Russian does *not* fit when compiled on my main desktop, and the linux machine i normally use for compiling is out of action at the moment so there will be a delay on russion im afraid.
