### ISSUE TITLE
boost mode temp not shown

### ISSUE THREAD

**Issue by corbolais** [Ralim/ts100#339]
Running latest firmware.

* **I'm submitting a ...**
  - [X ] Bug report

* **What is the current behavior?**
  - boost mode active. 
  - actual shown temperature is set temperature (320°C). 
  - actual measured temperature is boost temperature (420°C)

* **What is the expected behavior?**
  - shown temperature should reflect boost mode.

* **What is the motivation / use case for changing the behavior?**
  - user needs correct input.

* **What are you running:**
  - V2.05 PCB2
  - DC input, Vcc = 12.2V (6A max)

**Comment by Ralim** [comment]
Hi,

Can you clarify if the screen is not reading the correct temp back to you but the tip is actually heating to a higher temperature?

**Comment by corbolais** [comment]
Hi,
Thanks for your quick reply (and your ralim-ts100 fw as well :).

> Can you clarify if the screen is not reading the correct temp back to you but the tip is actually heating to a higher temperature?

Correct: screen tells 318°C, actual tip temp is 419°C.

Tip temp measured using HAKKO FG-101.

**Comment by Ralim** [comment]
Hi,
Can you confirm if you have used the tip calibration function at all?

If you exit soldering just after boosting, does the idle screen show the correct temperature?

Is the temperature correct when not boosting?

**Comment by corbolais** [comment]
Well, good thinking.

I *believed* it exec'd the temp calibration. But maybe it just didn't do it? I will recheck/redo temp calibration.

After a thought though, I'd say, temp calibration has positively been exec'd. As the measured temp does exactly match the boost temperature of 420°C.

**Comment by Ralim** [comment]
Hi,

Just trying to narrow down if it's a display in soldering mode issue, or if it's a general tip reading issue
