### ISSUE TITLE
Resting temperature (sleeping) set at 150ºC or 30ºC at least.

### ISSUE THREAD

**Issue by Batmonstro** [Ralim/ts100#374]
Resting temperature, after a certain set time has passed, such as one minute, does not assume the value that the user parameterizes. Usually stays at 150ºC or 30ºC lower !!!

* Firmware Verification = 2.05.01 (f716578)
* Board version = I'm not aware (???)

**Comment by dhiltonp** [comment]
Will be fixed by #275

**Comment by Ralim** [comment]
@Batmonstro @dhiltonp is correct here in that the coming PID changes he has made will fix this in the future.

Also I have edited your issue to be more readable, please try and maintain formatting :) (Not all of the text needed to be in title size font).
