### ISSUE TITLE
Cannot get logo to work.

### ISSUE THREAD

**Issue by ShotgunBurger** [Ralim/ts100#408]
- [x] Bug report

* **What is the current behavior?**
After I update with FW TS100_EN.hex released Aug 2nd my iron works great but after dragging in my hex file with the logo, the iron wont turn on at all, to fix it I re-flash with the firmware and it works fine.

Any ideas?

**Comment by Ralim** [comment]
The logo format changed at one point.
Regenerate your logo for with the latest software and try that again first. :)

**Comment by ShotgunBurger** [comment]
I'm creating the logo fresh each time I try  using the logo creator but it still doesn't work. I might just have to run the iron without any logo.

**Comment by Ralim** [comment]
Can you upload your logo HEX file here and I can test (it will need to be zipped)
Also can you provide the information you cut out of the issue, at the end (unit details, firmware details)

**Comment by ShotgunBurger** [comment]
Here is the logo.
[logo.zip](https://github.com/Ralim/ts100/files/2594683/logo.zip)

Here is the firmware I'm using.
[TS100_EN.zip](https://github.com/Ralim/ts100/files/2594687/TS100_EN.zip)

And the DFU is 3.43, that's all the info I have sorry.

**Comment by Ralim** [comment]
Hi, 
Looking at your logo file, You are using the old tool to convert the logo.
There is an updated tool in the releases section if you want an `exe` or you can use the python tool (which does often do a better job).

**Comment by ShotgunBurger** [comment]
Awesome, cheers.
