### ISSUE TITLE
Russian in v2.05.01 is not working

### ISSUE THREAD

**Issue by AlexGyver** [Ralim/ts100#409]
Hello! Firmware v2.05.01 Russian is lack of fonts! Only icons

**Comment by Reydan46** [comment]
To work, you need to recompile from source.
I recompiled in Win 10. [Here](https://www.dropbox.com/s/xbgp77pjamgr9rk/TS100_RU.hex?dl=0) is the working version.

**Comment by artemirq** [comment]
@AlexGyver Как мне кажется, оригинальная прошивка все же стабильнее.Так же нагревает жало быстрее

**Comment by dhiltonp** [comment]
@Reydan46 : so it works on the current branch?

**Comment by artemirq** [comment]
@AlexGyver Да, это удобно. Но вручную повысить температуру - парочка нажатий. Делов-то. Турбо режим не такая уж и киллерфича. В остальном родная прошивка такая-же или, скорее всего, даже лучше. Анимация, например, симпатичнее в родной. Настройки можно менять на лету в ласт версии
И еще, раз мы тут, хотел-бы поблагодарить за твой видео-контент и за сайт. Созидаешь не за деньги, а от души, как истинный творец. Все офигенно, продолжай в том же духе. Успехов 👍

**Comment by AlexGyver** [comment]
> @AlexGyver Да, это удобно. Но вручную повысить температуру - парочка нажатий. Делов-то. Турбо режим не такая уж и киллерфича. В остальном родная прошивка такая-же или, скорее всего, даже лучше. Анимация, например, симпатичнее в родной. Настройки можно менять на лету в ласт версии
> И еще, раз мы тут, хотел-бы поблагодарить за твой видео-контент и за сайт. Созидаешь не за деньги, а от души, как истинный творец. Все офигенно, продолжай в том же духе. Успехов

Спасибо) я лично без турбо режима уже пайку не представляю. А насчёт не за деньги, не надо делать поспешные выводы :)

**Comment by artemirq** [comment]
@AlexGyver Я про то, что твои видео наполнены идеями твоего вдохновленного разума. Есть блогеры, у которых идея видео основана на том, чтобы что-то разрекламировать и распиарить. То есть они тупо на максимум извлекают прибыль, а не хотят сделать что-то качественное и полезное для других, чем можно было-бы гордится

**Comment by AlexGyver** [comment]
> @AlexGyver Я про то, что твои видео наполнены идеями твоего вдохновленного разума. Есть блогеры, у которых идея видео основана на том, чтобы что-то разрекламировать и распиарить. То есть они тупо на максимум извлекают прибыль, а не хотят сделать что-то качественное и полезное для других, чем можно было-бы гордится

Здесь да, с душой)
