### ISSUE TITLE
25v 2amp Safe?

### ISSUE THREAD

**Issue by iLLiac4** [Ralim/ts100#410]
Quick question. Will 25V 2A power supply be harmfull for ts100 or can it be used saftely?

TNX

**Comment by Ralim** [comment]
Depends, if its regulated at 25V it *should* be fine. If its unregulated (and thus > 25V when not loaded) it will break the ts100.

**Comment by iLLiac4** [comment]
Aha ok.and is there a way to identify if it is regulated or not?
