### ISSUE TITLE
Display Brightness, OLED wear

### ISSUE THREAD

**Issue by cehteh** [Ralim/ts100#415]
Please edit this template and fill out all the information you can (where relevant). Failure to provide essential information can delay the response you receive.

* **I'm submitting a ...**
  - [ ] Bug report
  - [x] Feature request
  - [ ] Translation

* **Do you want to request a *feature* or report a *bug*?**
New feature.

* **What is the current behavior?**
Display is at fixed (maximum?) brightness.

* **What is the expected behavior?**
Would be nice to be able to configure the brightness. The current setting is pretty bight anyway. I would prefer something more dim. Reducing the brightness would also extend the OLED lifetime and reduce wear significantly. A quick glance on the datasheet and code shows that brightness is supported theoretically. Dunno if that actually works on the hardware.

Alternatively the Display could go into inverse mode every once a while (automatically toggle after each sleep or after N minutes, or by user setting). Per Datasheet this should be supported as well.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

***Steps to reproduce:***

1. 
2. 
3. 

***Video of problem if hard to reproduce***

* **What is the motivation / use case for changing the behavior?**
Dimmer display would be still well readable and having a more pleasing 'paperlike' appearance.  With the benefit of less burnout/wear on the OLED as well.

* **What are you running:**

On the idle screen, you can hold the settings button and it will show you the firmware version.

  - Firmware Version: 2.x
  - PCB Version: (1/2)
  - Power Supply (Voltage and Current Rating) :

* **Other information** 

If submitting graphics to go on the iron, please use BMP or PNG files over JPG.

**Comment by Ralim** [comment]
Brightness does work a little bit, but you sorta get like 4 levels of screen brightness, and in my testing the displays age about the same being off as they do on, and seem to just age over time :(

**Comment by Invictaz** [comment]
> Brightness does work a little bit, but you sorta get like 4 levels of screen brightness, and in my testing the displays age about the same being off as they do on, and seem to just age over time :(

I mean what can be the difference then with Samsung smartphone OLED's? I have a Samsung S3 from 2012 and it only has minor burn in and still full brightness. I have a Samsung YP-U3 which still has the brightness and one that is very dimm. 
What can be the issue?

The first generation OLED's did fade faster and burned in sooner (just like the first LG OLED tv's) but nowadays with pixel-shift, image retention cleanup and other techniques the longevity is improved?

**Comment by ia** [comment]
> What can be the issue?

@Invictaz, the issue is comparing [in case with _Samsung S3_] a color super AMOLED high resolution screen (while a screen is ~20% of the whole price of a modern smartphone) with a monochrome 96x16 screen (like `9616TSWC`) for ~1-2$.

> nowadays with pixel-shift, image retention cleanup and other techniques the longevity is improved?

Not for `9616TSWC` or `SSD1306`, because they don't have all of these features.
And, yes, OLED screens inside [supported hardware](https://github.com/Ralim/IronOS#supported-hardware) [have tendency to wear off](https://ralim.github.io/IronOS/Troubleshooting/#no-display-or-dots-on-the-display).

P.S. Sorry, but I will have to mark both of our comments as off-topic.

**Comment by Invictaz** [comment]
> > What can be the issue?
> 
> [@Invictaz](https://github.com/Invictaz), the issue is comparing [in case with _Samsung S3_] a color super AMOLED high resolution screen (while a screen is ~20% of the whole price of a modern smartphone) with a monochrome 96x16 screen (like `9616TSWC`) for ~1-2$.
> 
> > nowadays with pixel-shift, image retention cleanup and other techniques the longevity is improved?
> 
> Not for `9616TSWC` or `SSD1306`, because they don't have all of these features. And, yes, OLED screens inside [supported hardware](https://github.com/Ralim/IronOS#supported-hardware) [have tendency to wear off](https://ralim.github.io/IronOS/Troubleshooting/#no-display-or-dots-on-the-display).
> 
> P.S. Sorry, but I will have to hide both of our comments as off-topic.

Users that have the OLED not turning on after a few months of not using them? Must be environmental issues then? 
The pixel shift is just the OS moving the image, like the HT140 now already has, but only in standby mode.

**Comment by Ralim** [comment]
@Invictaz 

>Users that have the OLED not turning on after a few months of not using them? Must be environmental issues then?

Keep in mind, these screens sell for < $0.2US each in volume. So anything they can do to cut $0.00001 off the price; they do. 

I've had new-old-stock in a drawer be faded when I take it out, never having turned it on. While its keep in a reasonably climate controlled room. I suspect its most likely just the sealing between the two glass layers allows humidity/air in eventually and it slowly fades it out. Or maybe just some batches of the active ?fluid? (whatever is in there) just ages over time. 

It is best to see these cheap OLED's as having a shelf life, especially with companies that uses whatever the cheapest one of the day is.

(I will mark this off topic and lock after this, in future this is suited to discussions)
