### ISSUE TITLE
Makefile is broken, again

### ISSUE THREAD

**Issue by dogtopus** [Ralim/ts100#418]
Please edit this template and fill out all the information you can (where relevant). Failure to provide essential information can delay the response you receive.

* **I'm submitting a ...**
  - [X] Bug report
  - [ ] Feature request
  - [ ] Translation

* **Do you want to request a *feature* or report a *bug*?**

Report a bug.

* **What is the current behavior?**

Makefile is broken possibly due to the HAL update. The compiler tries to compile source code under `HAL_Driver/Src/Legacy/` and `HAL_Driver/Src/*_template.c` which causes this failure. It could be fixed by removing the offending files or add rules in the Makefile to exclude them.

* **What is the expected behavior?**

A working Makefile.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

***Steps to reproduce:***

1. Run `make`

***Video of problem if hard to reproduce***

Not applicable

* **What is the motivation / use case for changing the behavior?**

Not applicable

* **What are you running:**

Not applicable

* **Other information** 

If submitting graphics to go on the iron, please use BMP or PNG files over JPG.

**Comment by Ralim** [comment]
Ah yeah, I haven't done any command line builds since migrating to a newer HAL.

Feel free to pull request the changes, or otherwise ill get to this soon.

**Comment by avion23** [comment]
Same here with debian testing.

This commit doesn't work
> commit 873eb2a1e93e60c828643a16969852c21d32541c (HEAD -> master, origin/master, origin/HEAD)
Author: Ben V. Brown <Ralim@Ralimtek.com>
Date:   Sun Dec 16 18:13:59 2018 +1100
Move to latest HAL release trying to get I2C DMA to be more reliable, and known good point.
Cleans up some redundant calls as well to make some flash room.

This one still works
>commit b744f51e2d59d5cb88cf809dccca776e71d047a0
Author: Ben V. Brown <Ralim@Ralimtek.com>
Date:   Sun Dec 16 16:16:31 2018 +1100
Fix normal solder screen issues, disable I2C DMA pending some testing

**Comment by pjz** [comment]
I went to repro this and was unable to - in other words, it seems to work for me.  On Ubuntu 18.04, I just did `apt install gcc-arm-none-eabi` and then `make` worked for me, building `TS100_EN.{bin,elf,hex,map}` in the `Hexfile` directory.
