### ISSUE TITLE
Bring back ability to turn off the iron.

### ISSUE THREAD

**Issue by Jahnkeanater** [Ralim/ts100#423]
The default firmware had the ability to return to the main menu by pushing both buttons at the same time. This made it possible to turn off the iron without unplugging it. It was useful to still see the temp while it cooled down.

**Comment by GnFlala** [comment]
Just hold the button near screen for a while

**Comment by Ralim** [comment]
The dual button exit hasnt been removed and should still work ? Or hold the read button (has been in the firmware for over 6 months)
