### ISSUE TITLE
python converted logos, not flashable

### ISSUE THREAD

**Issue by noemu** [Ralim/ts100#437]
Please edit this template and fill out all the information you can (where relevant). Failure to provide essential information can delay the response you receive.

* **I'm submitting a ...**
  - [x] Bug report
  - [ ] Feature request
  - [ ] Translation

* **What is the current behavior?**
with python created boot-logo result in an "err" file, after flashing.
I compiled the gui-logo-converter and this program creates a perfect flashable file. 

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

***Steps to reproduce:***

1. ```python img2ts100.py in.png out.hex```
2. drag and drop hex on the ts100 in dfu mode
3. receive err file

* **What are you running:**

  - Firmware Version: 2.05
  - PCB Version: 2
  - Windows 10
  - Python 3.6.5

* **Other information** 

[lgos.zip](https://github.com/Ralim/ts100/files/2797129/lgos.zip)

**Comment by Ralim** [comment]
Hi, can you upload the files made by the python code and the c# tool for comparison? Both appear to work for me here, so wondering if its to do with your computers setup?

**Comment by noemu** [comment]
[csharp.zip](https://github.com/Ralim/ts100/files/2798867/csharp.zip)

**Comment by m-kozlowski** [comment]
Had similar problem. changing line terminators to CRLF solved issue for me.
