### ISSUE TITLE
Temperature Update Rate not selectable on Alpha 1.17

### ISSUE THREAD

**Issue by Trezona** [Ralim/ts100#45]
Hi Ralim, love the new fonts!!
I cannot seem to make any changes to the "Temperature Update Rate" on alpha 1.17
Its stuck at "F"

**Comment by Ralim** [comment]
I'm an idiot, should be patched (I just updated the files for the 1.17 alpha. Can you download and test again. Thank you for spotting this so fast.

**Comment by Trezona** [comment]
No problem at all, will test now!

**Comment by Trezona** [comment]
Working great! Thanks very much.

**Comment by Ralim** [comment]
No problem, thanks for spotting my typo so quickly. :)
