### ISSUE TITLE
Need help uploading my logo to my ts100 soldering iron 

### ISSUE THREAD

**Issue by Gamerx007** [Ralim/ts100#454]
Bug Report 

Need help uploading my logo to my ts100 
I am also trying to find and run the exe variant of the editor program
I have looked under the releases section and have not been able to find it
I'm submitting a ...

  
all help would be most appreciated

Thank you for your time in advance

I am running windows 10 Pro 64 bit 

  - Firmware Version: 2.06
  - PCB Version: (1/2)
  - Power Supply (Voltage and Current Rating) : 19v

* **Other information** 

[ts 100 logo.zip](https://github.com/Ralim/ts100/files/2948923/ts.100.logo.zip)

![ts100-logo-sainsmart-no background](https://user-images.githubusercontent.com/48368689/54078500-0ac9c100-4297-11e9-8d9e-a9996be3e8ff.png)

![Editior ts100 ](https://user-images.githubusercontent.com/48368689/54078586-7d876c00-4298-11e9-9d59-a170413ee662.png)

**Comment by physi** [comment]
Hi,
I found the Logo Editor in Rel. 2.02:

https://github.com/Ralim/ts100/releases/download/v2.02/TS100.Logo.Editor.exe

HTH
