### ISSUE TITLE
v2.06 - Cool down doesn't blink

### ISSUE THREAD

**Issue by jj-uk** [Ralim/ts100#464]
v2.06

When the iron enters cooling down mode (hold the button or when sleep times out) the screen no longer blinks. The blink when cooling setting is checked but appears to be ignored.

Also "warning HOT!" is no longer displayed when cooling, was this removed?
Nothing on the screen indicates that the iron is in cooling down mode except the temperature can be seen to be decreasing.

**Comment by michalszymura** [comment]
#416

**Comment by Ralim** [comment]
Closing this in favour of #416 and #476
