### ISSUE TITLE
The hex file with the bulgarian translation is broken. show monkeys 

### ISSUE THREAD

**Issue by issyvarsano** [Ralim/ts100#472]
Please edit this template and fill out all the information you can (where relevant). Failure to provide essential information can delay the response you receive.

* **I'm submitting a ...**
  - [ ] Bug report
  - [ ] Feature request
  - [x ] Translation

* **Do you want to request a *feature* or report a *bug*?**

The hex file with the bulgarian translation is broken. show monkeys 

* **What is the current behavior?**
its showing wrong symbols instead if what should be

* **What is the expected behavior?**

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

***Steps to reproduce:***

1. 
2. 
3. 

***Video of problem if hard to reproduce***

* **What is the motivation / use case for changing the behavior?**

* **What are you running:**

On the idle screen, you can hold the settings button and it will show you the firmware version.

  - Firmware Version: 2.x
  - PCB Version: (1/2)
  - Power Supply (Voltage and Current Rating) :

* **Other information** 

If submitting graphics to go on the iron, please use BMP or PNG files over JPG.

**Comment by Ralim** [comment]
Hey @issyvarsano 
Could you have a go of the latest release RC that was put up?
