### ISSUE TITLE
Cant flash firmware

### ISSUE THREAD

**Issue by feivur** [Ralim/ts100#473]
- [v] Bug report
  - [ ] Feature request
  - [ ] Translation

I press button nearest to the tip. Plug usb cable. On display appears DFU:3.43. On computer appears disk with name C4DFCDEF, 2Mb size, 2Mb free. Then I drag-n-drop v2.06-RC4 .hex file to this disk. Then disk disconnect from system and appears message about file too large to this file system.
After this iron not boot up when i connect the power. Same behaviour on any firmware version.
Windows 10 64bit

**Comment by Ralim** [comment]
Hi,
Could you please confirm which operating system you are using?
Have you searched the previous GitHub issues raised about this? Almost always this is due to how your computer is configured / setup

**Comment by feivur** [comment]
I checked os version:
Windows 10 64bit, build 1809

**Comment by feivur** [comment]
I tryed on other PC with Windows 10 64bit, build 1803, and there is no problem, iron successfully flashed. 
Dont know, what was cause of fail on first PC. Close issue.

**Comment by 1iggy2** [comment]
Same issue Windows 10, Version 1903. The file explorer from the TS100 closes immediately. Attached is image of error message, file name, and Windows Update Page.
![Error TS100](https://user-images.githubusercontent.com/46946416/63294164-a3795980-c297-11e9-81e2-60e7673ef655.PNG)

**Comment by 1iggy2** [comment]
Tried on another identical system. Same windows version, same cable. Worked like a charm. I don't know if this will help troubleshooting this issue in the future if needed, but the computer that worked is an Asus Laptop, been in use for 2-3 years. The computer that didn't work is a desktop built in May 2019, B450 Tomahawk, Ryzen 2600X, RTX 2060, 32 GB RAM.
