### ISSUE TITLE
No LOGO EDITOR HEX.EXE file

### ISSUE THREAD

**Issue by CaliAirFPV** [Ralim/ts100#474]
I'm trying to customize my TS100 with a logo but i cant find the logo editor hex file download.

**Comment by TheUntouchable** [comment]
This is the latest logo editor I found:
https://github.com/Ralim/ts100/releases/download/v2.02/TS100.Logo.Editor.exe

But at least I am not able to flash even the default logos, I always got an .err file back.

**Comment by richrd** [comment]
I was also looking for the logo editor. I went through the latest releases and found it in an older release. For me it worked fine. No issues at all.

**Comment by TheUntouchable** [comment]
Youre right, just tried it with the linked logo editor from my post and it worked this time, funny :D
