### ISSUE TITLE
My ts100 doesnt work

### ISSUE THREAD

**Issue by colbycarp325** [Ralim/ts100#480]
i put a the latest firmware on it, and now it doesnt even turn on, can someone please give me the old firmware, thanks.

**Comment by whitehoose** [comment]
Bit difficult when you don't say what your old f/w was (ralim's?... stock? version? ... language?).
Easier if you help yourself. 
https://github.com/Ralim/ts100/releases
http://www.minidso.com/forum.php?gid=52
