### ISSUE TITLE
TS80 doesn't standby correctly

### ISSUE THREAD

**Issue by Bullone** [Ralim/ts100#506]
Please edit this template and fill out all the information you can (where relevant). Failure to provide essential information can delay the response you receive.

* **I'm submitting a ...**
  - [x] Bug report
  - [ ] Feature request
  - [ ] Translation

* **Do you want to request a *feature* or report a *bug*?**

* **What is the current behavior?**
After flashing the master code TS80 doesn't go to standby mode correctly: it keep about 80C 

* **What is the expected behavior?**
The expected behaviour should be the temperature goes down till ambient temperature 

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

***Steps to reproduce:***

1. Clone the repo and build the code using make -j8 lang=EN model=TS80 command
2. Flash the .hex file (device say v2.06 19-08-19)
3. After connecting the TS80 to the power supply it remain at about 80C even if in standby mode

***Video of problem if hard to reproduce***

* **What is the motivation / use case for changing the behavior?**

* **What are you running:**

On the idle screen, you can hold the settings button and it will show you the firmware version.

  - Firmware Version: 2.0.6 19-08-19 (current master branch)
  - PCB Version: TS80
  - Power Supply (Voltage and Current Rating) : 9V on stock QC3.0 supplied

* **Other information** 

If submitting graphics to go on the iron, please use BMP or PNG files over JPG.

**Comment by Ralim** [comment]
Hey,
Can you tell me which tip you are using?

This is the code that keeps power banks alive, putting too much power out.

Its intended to be slightly less than the power required to maintain the tip, so that the tip does cool down, but by pulsing small amounts of power it keeps power banks from going to sleep.

**Comment by Ralim** [comment]
This is fixed somewhat in the testing power branch. Not ready for prime time yet, but a fix i coming :)

**Comment by Bullone** [comment]
Great! Thank you for keep me aligned :)

Il giorno lun 21 ott 2019 alle ore 07:49 Ben V. Brown <
notifications@github.com> ha scritto:

**Comment by Ralim** [comment]
This should be fixed in the latest release, re-open if its not fixed :)

**Comment by Bullone** [comment]
Thanks!
