### ISSUE TITLE
Feature request: Autostart heat to sleep temperature

### ISSUE THREAD

**Issue by awigen** [Ralim/ts100#51]
It would be nice if the autostart setting was enabled there was also an option to startup in sleep mode.

1. Power is applied, soldering iron heats to sleep temp
2. Soldering iron is picked up and heats to work temp

**Comment by Ralim** [comment]
Yep, can do :)

**Comment by Ralim** [comment]
I have added this option in the latest tester version.
However, I don't think this work overly well as the accelerometer is rather noisy at startup as it settles into operation. Curious to see your thoughts on this.

**Comment by Vidalcris** [comment]
What about using a delay at start when this option is enabled ?
The delay should be cancel if we press tip button to heat the iron.
10 seconds could be fine then ;)

**Comment by awigen** [comment]
Masking the the accelerometer for the first 5-10 seconds should do the trick.

**Comment by Ralim** [comment]
Yes I agree that masking the input for the first 10 seconds would work, 
Ill make up a testing build to test this soon.

**Comment by Ralim** [comment]
@awigen @Vidalcris The latest push includes a mask on the accelerometer. Can you please test and check it works on your devices?

**Comment by Vidalcris** [comment]
It work well on my side ;)

**Comment by Ralim** [comment]
I'm going to close this for now as @Vidalcris has found it working, and it works on both of my units. 
Anyone can re-open this if there are any future issues with this.
