### ISSUE TITLE
TS100 only displaying a maximum of 2 watts?

### ISSUE THREAD

**Issue by HondaRider01** [Ralim/ts100#512]
Hey everyone, I'm new here, so I apologize if I don't do this correctly...

* **I'm submitting a ...**
  - [ x  ] Bug report 
  - [ ] Feature request
  - [ ] Translation

* **Do you want to request a *feature* or report a *bug*?**

Possibly a bug, or possibly a hardware issue?  I'm honestly not sure.

* **What is the current behavior?**

Just purchased this UYCHAN TS100 recently, from Amazon.  With Ralim firmware installed, and using the "detailed solder screen," the wattage reading never displays more than 2W.  While the iron is heating from room temp, it will only display a maximum of 2W.  When soldering large connections (12AWG to XT60 connector, for example), the reading will never exceed 2W.  The power supply that I use does not effect this seemingly low 2W reading that I get. 

* **What is the expected behavior?**

The TS100 is rated at 65W, so I would expect to see higher readings than 2W on the display, especially when soldering large connections.  

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

***Steps to reproduce:***

1. 
2. 
3. 

***Video of problem if hard to reproduce***

* **What is the motivation / use case for changing the behavior?**

* **What are you running:**

On the idle screen, you can hold the settings button and it will show you the firmware version.

  - Firmware Version: 2.06
  - PCB Version: (1/2)             <--  I'm not sure about this one...
  - Power Supply (Voltage and Current Rating) :  19.3V

* **Other information** 

I have tried removing and reinstalling the Ralim firmware, which didn't make any difference.  I should mention that the iron seems to solder very well, despite the low readings of 2W.  I'm not sure if this is actually a problem or not... ?  But it seems wrong to me.  I've attached a picture of the display while the iron is heating up, which shows the maximum reading of 2 watts that I'm  getting.

Thank you for your time, I greatly appreciate it!
Tim

If submitting graphics to go on the iron, please use BMP or PNG files over JPG.

![TS100 detailed display](https://user-images.githubusercontent.com/56597588/66842799-b9ff0280-ef20-11e9-9ef9-087bc65fe019.jpg)

**Comment by Ralim** [comment]
This is a known bug,  it will be fixed in next release.
It's cosmetic only. :)
