### ISSUE TITLE
Less sensitive timings for simultaneous button press?

### ISSUE THREAD

**Issue by kimble4** [Ralim/ts100#52]
I'm finding that pressing both buttons simultaneously is very unreliable.  Maybe it's my hands, maybe it's the quality of the switches, but about half the time I attempt to press both buttons simultaneously it is read as a press of whichever button happens to trigger first.  (This is particularly annoying if you want to get into the Extras menu and accidentally end up with the iron heating up.)

Presumably this is a simple constant that can be tweaked.  Not sure if it's worth having another settings option for...?

**Comment by awigen** [comment]
I second that, I find the timing quite sensitive.

**Comment by Ralim** [comment]
@awigen @kimble4 Can you test the latest release if it's easier for you?
It's hard for me to test this apparently :/

**Comment by Vidalcris** [comment]
Way better imo ;)

**Comment by kimble4** [comment]
Yep, that's solved it for me.  Brilliant!

**Comment by Ralim** [comment]
Awesome! Ill close this, but open it if it gets harder again :)
