### ISSUE TITLE
[FR] Marking the last value before an option will roll over.

### ISSUE THREAD

**Issue by JohnEdwa** [Ralim/ts100#536]
* **I'm submitting a ...**
  - [x] Feature request (as quickly discussed in #517)

* **What is the current behavior?**

    Currently, a value will roll over with no indication, e.g the Boost temperature will go `440 -> 450 -> 250`, requiring the user to memorize the max and scroll though all of the values again. 

    The "Press-and-hold" functionality will also just breeze past this max at full speed.

* **What is the expected behavior?**

    It would be helpful to mark the highest value before it rolls over. Again with the Boost, going `440 -> [450] -> 250`. That way the user will immediately know "This is the highest value, it can't go higher than this" and doesn't have to scroll through them again. Bolding, italicizing, inverting the colours, adding brackets, something that is possible to implement while clearly indicating a difference.

   Additionally, the "Press-and-hold" should stop at the maximum value. Another possibility is to pause for a second, then roll over, pause on the lowest value for a second, then continue.

**Comment by paulfertser** [comment]
@JohnEdwa , @Swyter please test if you like the UX this way. I have no idea how to gather feedback of the other users as there's no project mailing list apparently.
