### ISSUE TITLE
Auto Start feature: True/S?/False, how to set to S? 

### ISSUE THREAD

**Issue by bl4k1st** [Ralim/ts100#545]
The TS100 could autostart the soldering.
The Help text for Auto Start reads T=Soldering, S= Sleep Mode, F=Off

That would mean, True, S= ?, False.

I only have a True/False Checkbox for autostart, how can I set S=Sleep?

latest firmware 2.07

**Comment by Ralim** [comment]
Hmm, 
didn't realise this was missing from the menu, fairly sure the code paths are still there otherwise.
I'll have a dig into this.

**Comment by ricktendo** [comment]
Help text is inaccurate, it says the options are: T=Soldering, S= Sleep mode,F=Off

But I only see options "M", "A" and "S"

Also please correct the spacing because this triggers my OCD!

**Comment by Ralim** [comment]
@ricktendo Which language did you use? This text is in the translation files, and its also up to the translation file to pick the letter. :) (Your welcome to use the github editor to create a PR if you have time)

**Comment by ricktendo** [comment]
@Ralim I am referring to v2.08 English version.

**Comment by Nu11u5** [comment]
Now the behavior seems swapped (based on previous comment).

The help text says "A=Soldering, S=Sleep, M=Off", but the menu options are "S", "F", and "T".

**Comment by Ralim** [comment]
@Nu11u5 Please feel free to open a PR to fix the menu text if you get time :)
Its fairly easy as you can edit it on github.com

**Comment by Firebie** [comment]
This is already fixed in post-commits after 2.08.1, just not yet released.

**Comment by colesnicov** [comment]
https://github.com/Ralim/ts100/issues/635#issuecomment-636218495
