### ISSUE TITLE
Screen blinking super fast in sleep mode

### ISSUE THREAD

**Issue by Vidalcris** [Ralim/ts100#56]
When the temperature is under 65°C the screen start to blink very very fast.
That happen only on sleep mode (my delay is 10sec)

Edit : problem do not occure if the screen blink is not activated btw ;)

**Comment by Ralim** [comment]
hmm, right. I'll fix this in a few hours.

**Comment by Ralim** [comment]
... Or i can fix it now :P Can you test the newest release?

**Comment by Vidalcris** [comment]
testing right now.

**Comment by Vidalcris** [comment]
Where are u from ?

**Comment by Vidalcris** [comment]
The screen is not blinking anymore on sleep mode or i did something wrong ?

**Comment by Ralim** [comment]
The screen is only mean to blink in the cooling mode at the moment? The screen blinking on sleep was an accident.

**Comment by Vidalcris** [comment]
ok so its working now ;)
(i contacted you on facebook if you are ok to add me ;) )

**Comment by Ralim** [comment]
Yeah its all good now :)
I dont really use facebook that much these days :/
