### ISSUE TITLE
Polish translation advanced idle display

### ISSUE THREAD

**Issue by TurboFlea** [Ralim/ts100#597]
Please edit this template and fill out all the information you can (where relevant). Failure to provide essential information can delay the response you receive.

* **I'm submitting a ...**
  - [X] Bug report
  - [ ] Feature request
  - [ ] Translation

* **Do you want to request a *feature* or report a *bug*?**
Just report a bug

* **What is the current behavior?**
Advanced display on idle screen when using Polish translation, doesn't fit on the screen. Set temperature is beyond right screen edge showing only first digit.

* **What is the expected behavior?**
When using English translation you can see all 3 digits of set temperature, I would expect inb any translation to be able to see set temperature not just the first digit of it.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
Enable advanced idle display while using PL translation and see the issue on idle screen

***Steps to reproduce:***

1.Go settings
2.>advanced settings
3.>enable display advanced information on idle screen.

***Video of problem if hard to reproduce***
N/A

* **What is the motivation / use case for changing the behavior?**
To see set temperature on idle screen. 

* **What are you running:**

  - Firmware Version: 2.08

**Comment by Ralim** [comment]
I don't maintain the translations  personally ( I only understand English).
Please feel free to submit a PR to edit the translation file to adjust the text to fit :)
