### ISSUE TITLE
Question / Feature request: lowest min temp

### ISSUE THREAD

**Issue by alex-belyaev** [Ralim/ts100#620]
* **I'm submitting a ...**
  - Feature request/Question

* **Do you want to request a *feature* or report a *bug*?**
 I would like to know if is it possible to make lower limit to like 20 or 30 C. Is there any hardware limitation to have 50C low limit?
 I needed so low temp to work with jewelry wax.

**Comment by Ralim** [comment]
Going to close this as the next firmware will include this (Thanks to @Firebie)
