### ISSUE TITLE
Watt meter error

### ISSUE THREAD

**Issue by Scoredx** [Ralim/ts100#626]
* **I'm submitting a ...**
  - [x ] Bug report
  - [ ] Feature request
  - [ ] Translation

* **What is the current behavior?**

After calibrating voltage while I powered the iron by USB the power meter shows max 3.3 W or 0 

***Steps to reproduce:***
1. fw >2.0.6 rc5
2. calibrate only powering by usb

**Comment by Ralim** [comment]
Hello,
You have cut out a lot of the template information, what device are you using? 2.0.6 rc5 is over 6 months old, and is not supported. If you can replicate this issue on a newer firmware i can look into it.

The watt meter is an _estimate_ based on average tip resistance, so there is some expected variance in it. However it should not act like this.

Do note that on the TS100 it does not support soldering using the USB port, and as such voltage calibration is only intended for when running this iron in spec - 12-24V.
