### ISSUE TITLE
unify behavior of certain menu entries

### ISSUE THREAD

**Issue by discip** [Ralim/ts100#642]
* **I'm submitting a ...**
 - [x] suggestion

* **Do you want to request a *feature* or report a *bug*?**
I suggest to unify the appearance / handling of certain menu entries.

* **Current behavior  vs  expected behavior?**
In the **`Advanced options`** menu there are at least 2 different solutions for mainly the same thing.
The 'thing' is on one hand to ***activate the feature*** and on the other to ***set*** the corresponding ***value***.

In particular the following 2 entries treat almost the same thing differently:
## 1. Power limit
  * **`Enable power limit [x]`**
  * **`Power limit {value}`**
These 2 could be combined into one entry, just like for example: **`Shutdown timeout`** *{**Off**, 1M ...}*
This has to be changed later on to the way, which is described in **3**.

## 2. Power pulse
  * **`Power pulse W {[ ],value}`**
Although this one is kind of combined, but not as sleek as for example: **`Shutdown timeout`** *{**Off**, 1M ...}*
This out of place empty box just 'ruins' it.
This also should be changed later according to the way, which is described in **3**.

## 3. Overall behavior of setting values
Because of the fact, that you have to start over every time you push the corresponding button to often and cycle trough from the beginning to the desired value. I think it would more convenient to be able to set the values, almost like it is done in the original firmware of *miniware*.

The actual **appearance** would barely **change**, just the way **values are set** would change.

Please let me explain:

1. For going to the next entry you would still have to press the ***B*** button. And for selecting things or changing values you would also still use the button ***A***.

No changes so far! 😁

2. Now to alter values after having entered this *mode* by using ***A***, you now would be able to **increase** or **decrease** the value by pressing ***A*** or ***B*** respectively. And after doing so, both buttons would have to be pressed at the same time, to exit this *mode*.

### Please note: I am not referring to the way it is done for **`Modify tip gain`**, *this should also be changed, to unify the appearance!*

It should rather stay the way it is done for **`Shutdown timeout`** *(Description **text** and the changing **value** can be seen at the **same time**.)*, with the **slight change** in making the value in *edit mode* **blink**! 

* **What is the motivation / use case for changing the behavior?**
This one is as well motivated by the wish to have a more consistent look and feel of this beautiful piece of software.

I hope anyone is getting my point and it is not to far off track. 😅

* **What are you running:**
  - **TS80**
  - Firmware Version: **v2.10.1**
  - PCB Version: **2**

**Comment by Ralim** [comment]
These are all very logical.
I'm currently focusing on the TS80P but after its up to basic functionality these are probably next on the list :)

**Comment by discip** [comment]
@Ralim 
Wow that's great news!
If I had to choose, I would definitely go with the **TS80P**.
But I am also curious about the above mentioned menu adjustments, since it would also affect the **TS80P**. 😊

**Comment by Ralim** [comment]
Yeah my TS80P did arrive, but my quick (lol - multi day) port of existing code didnt work first go so still waiting for some breakout boards for usb-C to arrive so I can decode whats actually happening on the PD bus.

**Comment by discip** [comment]
Ah you have already invested effort into *pre-building* code, that is definitive laudable!
I hope you do not have to rewrite everything! 😅
I cant wait to see the first release, but I appreciate it, if you take your time, since nobody wants the **developers device** being  *bricked*.

**Comment by Ralim** [comment]
So what I have done so far is to unify everything to combine the setpoint with the value.

I'm not certain if I want to do the miniware style of entering and exiting setup mode as that feels very _slow_ to do.. But is that because im working through the menu a lot ?

**Comment by discip** [comment]
@Ralim
**Thank you** for considering this suggestion. 👍
In my opinion, the *demand for consistency* is covered! 😊

ps: I like the blinking scrollbar when the last entry is reached and the logical behavior of neither pausing nor blinking when the list consists of only 2 entries.

**Comment by Ralim** [comment]
Glad its a bit more consistent at least :)

Thank @paulfertser for the sweet menu pause and scrollbar work :)

**Comment by discip** [comment]
@paulfertser
Thank you!
