### ISSUE TITLE
Display content not centered anymore on TS100

### ISSUE THREAD

**Issue by fiechr** [Ralim/ts100#658]
I've just flashed v2.10.1 onto my TS100. Everything seems to work fine, but all symbol and texts on the screen are shifted to the bottom right (see pictures). On some screens the text on the left is cut off and there is some kind of dot on the right.

![IMG_20200618_202156](https://user-images.githubusercontent.com/12040376/85058507-83117880-b1a2-11ea-8d43-dab7143e402a.jpg)

![IMG_20200618_202117](https://user-images.githubusercontent.com/12040376/85058513-83aa0f00-b1a2-11ea-8cba-bd6724163b8c.jpg)

I did not configure anything, so this is the default state after factory reset.

I don't know what hardware revision my TS100 is, but I can find out, if necessary.

**Comment by paulfertser** [comment]
The dot on the right is actually a scrollbar indicator. What version is centered properly on your hardware?

**Comment by fiechr** [comment]
v2.09 didn't had that issue.

**Comment by paulfertser** [comment]
Photos I find on the Internet show bottom-aligned (not centered) on factory firmware too. Can you please retest with other firmware versions and make some photos to make sure it can indeed be different? The OLED datasheet says it has 16 pixels height and your photo shows all 16 pixels in action so I can't see how it can work any other way.

**Comment by paulfertser** [comment]
I see how Temp change short and Temp change long are truncated, that's a bug all right.

**Comment by paulfertser** [comment]
Please make photos of other screen anomalies, so far I do not see any.

**Comment by fiechr** [comment]
OK, I will downgrade and report back.

**Comment by fiechr** [comment]
You are correct! The position of the text is the same with the older version.

The only real bug seems to be the truncated text for these two strings. I couldn't find any other errors. I'm very sorry for the confusion! :-(

I understand now the purpose of the dot, but I'm unsure if it is actually useful. But that's just me.
