### ISSUE TITLE
TS100 - When trying to calibrate temperature, weird random number shows up and it cancels instantly - Firmware v2.10.1

### ISSUE THREAD

**Issue by Phil-2020** [Ralim/ts100#668]
Please edit this template and fill out all the information you can (where relevant). Failure to provide essential information can delay the response you receive.

* **I'm submitting a ...**
  - [X ] Bug report
  - [ ] Feature request
  - [ ] Translation

* **Do you want to request a *feature* or report a *bug*?**
Bug

* **What is the current behavior?**
When trying to calibrate the temperature via the menu, when one tries to go ahead after the room temperature notice, when i want to go ahead, i get the (. . . . ) and then immediatly after a random number between 800 - 1500 shows up and then instantly i'm back at the previous menu

* **What is the expected behavior?**
I expect the temperature calibration to start, but it doesn't.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

***Steps to reproduce:***

1. Go into settings menu
2. Go into advanced options
3. Click "calibrate temperature ?"
4. Click while room temperature note is displayed
5. Loading occurs: ( . . . . ) 
6. Random number is shown for example: ( [✓] 899 )  Usually between around 800 and 1500
7. After half a second or less i get thrown back to the room temperature note

* **What are you running:**

On the idle screen, you can hold the settings button and it will show you the firmware version.

  - Firmware Version: v2.10.1
  - PCB Version: (1/2)
  - Power Supply (Voltage and Current Rating) : 24V, 3 Amps

* **Other information**

If submitting graphics to go on the iron, please use BMP or PNG files over JPG.

**Comment by Ralim** [comment]
Hello 😅

That's _normal_ behaviour.

The number is your uV offset value between the ideal and real models.

The out of box calibration is 900 off memory which should be close for most units.

**Comment by Phil-2020** [comment]
> 
> 
> Hello 😅
> 
> That's _normal_ behaviour.
> 
> The number is your uV offset value between the ideal and real models.
> 
> The out of box calibration is 900 off memory which should be close for most units.

I'm glad, i realized that after a day of thinking about things and looking at a Youtube video.

But i seriously remember that there was a temperature kind of tuning that took like a minute or a few.

Was that a PID tuning ?

Is there temperature PID tuning still on the newest firmware ?

If yes, is it recommended to do it ?

**Comment by Ralim** [comment]
It wasnt a PID tune, but was more of a two point tuning that has been dropped as almost no-one was any more accurate with it than the single point (and the few that were, i feel could have been luck).

Would like to revisit tip calibration again _after_ getting TS80P stuff out the door a bit more.

Generally to _most_ users you dont need to do anything :)
