### ISSUE TITLE
Report sensor error if the tip is not plugged in/broken

### ISSUE THREAD

**Issue by dogtopus** [Ralim/ts100#67]
This feature is available on the official firmware (it will display something like "SEN ERR" instead of showing a wrong temperature reading)

**Comment by Ralim** [comment]
Hi,
Yes this certainly can be added. Can I ask if you have had a tip fail? (I've not heard of any yet so just curious)

**Comment by dogtopus** [comment]
No I didn't. I only tested the case where the tip is unplugged.

**Comment by Ralim** [comment]
This has been added to the new firmware, because of the way this works on the idle screen the over temp will occur first followed by the tip error screen, unfortunately. Working on that now w:)
