### ISSUE TITLE
Firmware does not work on SainSmart Pro 32 (TS100 clone)!

### ISSUE THREAD

**Issue by andreich26** [Ralim/ts100#671]
The firmware v2.10.1 is installed without errors, but the soldering iron does not warm!

**Comment by Ralim** [comment]
Hello,

Can you provide some more details?
I do not own any clone units to test against so curious as to what is different on these.

Could you list out all of the items in the debugging menu?

**Comment by andreich26** [comment]
Video https://youtu.be/D66w7igqEzo
the soldering iron does not turn off on the B button
the soldering iron does not heat

**Comment by agatti** [comment]
That's odd, I've got the very same iron and it has always worked with this firmware for the past couple years...

**Comment by Ralim** [comment]
If you are still looking to solve this:

If you load the miniware firmware onto the unit does everything work correctly?
Could you try the latest firmware to see if the issue still persists?
