### ISSUE TITLE
Settings only is cold state

### ISSUE THREAD

**Issue by mikko70** [Ralim/ts100#674]
Please help. i´m not programmer
I know there is quite impossible change anything , but if i  want settings available only when i´m not soldering and
settings menu is disabled during job.

Can it do like

GUIThread.cpp

672            case BUTTON_B_SHORT:
          	      if (buttonLockout= false)
673                enterSettingsMenu();  // enter the settings menu
674                buttonLockout = true;
675                break;
676           default:
677                break;
678        }

**Comment by Ralim** [comment]
What are you trying to acheive?
What is your usecase?
