### ISSUE TITLE
TS80 Doesn't Reach Final Temperature

### ISSUE THREAD

**Issue by mmehrle** [Ralim/ts100#676]
I'm running the most up to date version of the TS80 firmware. It's a new purchase - only a month old and used a handful of times. 

Problem: Max temp is set to 440C but it stops at ~330C. When I plug it in/out then it works again intermittently. Not sure if this is a firmware or a hardware issue. Sometimes swapping USB outputs (on the same charger) also helps. 

Thanks in advance for any pointers.

**Comment by Ralim** [comment]
@mmehrle 
What voltage are you running the iron at?
It sounds like your using 5V rather than the rated 9/12V.
If your running at 5V it will behave exactly like this.
