### ISSUE TITLE
Improving the code

### ISSUE THREAD

**Issue by gidimiz** [Ralim/ts100#7]
Hi.

Great job!
For ver. 1.08, please add the following that will shut down the TS100 after 30 min of inactivity in SLEEP to COOLING ( I reused your code .. )
Modes.c line: 158
`		//We need to check the timer for movement in case we need to goto COOLING
			if (systemSettings.movementEnabled)
				if (millis() - getLastMovement()
						> (30 * 60000)) {
					if (millis() - getLastButtonPress()
							> (30 * 60000)) {
						operatingMode = COOLING;
						return;
					}
				}`
You can also improve this by adding an option in the OLED to have it on ( 1  -60 ) or off ( 0 ).
Thanks.

**Comment by Ralim** [comment]
Hi, let me know if you have any further suggestions. :)
