### ISSUE TITLE
How to open TS80p?

### ISSUE THREAD

**Issue by Makhaira** [Ralim/ts100#714]
I was about to start playing with this firmware but my screen just died. There's some helpful stuff on here about sourcing replacements, but for the life of me I can't get the TS80p open. So far I've removed the little allen screw and tried gently prising up the panel around the screen without success - any tips please?

**Comment by GreekGeorge** [comment]
If it's anything like the TS80, there's a hidden screw under the button cover.
Please check this video:
https://youtu.be/83STpUXHilk?t=232

**Comment by Makhaira** [comment]
Hero thank you

**Comment by hwater** [comment]
thanks also for this guide - my display getting darker and darker. i have seen, the oled inside gets dry and transparent at the corners

**Comment by whitehoose** [comment]
If it's an 80p presumably it's still under warranty - why not contact your seller?

**Comment by hwater** [comment]
no it is an TS80

**Comment by whitehoose** [comment]
I was aiming at the OP - but good to know :)
