### ISSUE TITLE
TS100 QUERY

### ISSUE THREAD

**Issue by greverfbrayer** [Ralim/ts100#716]
![Captura](https://user-images.githubusercontent.com/56897711/99019399-38661380-252a-11eb-85ba-597fd6f94408.PNG)
It is normal that when connecting the ts100 to the computer it does not recognize it.
There should be no "CONFIG" note.
Or is it due to the latest update I upload?
![image](https://user-images.githubusercontent.com/56897711/99019787-1e790080-252b-11eb-9de1-efbb6c522fa1.png)

**Comment by Ralim** [comment]
If you are using this firmware (not the official firmware). 

This is entirely normal as noted in the readme there is NO USB in normal operation.

**Comment by greverfbrayer** [comment]
@Ralim I was scared, I thought I blew it. Thank you. I am now calmer.
