### ISSUE TITLE
Display tip temperature when holding tip up

### ISSUE THREAD

**Issue by EricJanVanDenBogaard** [Ralim/ts100#73]
To have the display show tip temperature while holding the TS100 vertical with tip up,
would be a handy feature, this feature should be available in all modes also startup/idle mode,
(also when just plugging in from a short disconnection)
the vertical & tip up position would not give conflict with other functionality.

**Comment by av8er** [comment]
Why make this so complicated? If the iron is plugged in with the temperature above 60c or whatever value we pick, just have it display the temp until it's below.

**Comment by Ralim** [comment]
I believe the intent behind this was to provide an easy way to view the temperature no matter what temperature it is at?

**Comment by EricJanVanDenBogaard** [comment]
didn't thought this one over i guess av8er is right, that should be enough. close this one,
does the voltage still need to be calibrated for the cell protection voltage, when setting the cell count ?
