### ISSUE TITLE
List version number in the menu [suggestion]

### ISSUE THREAD

**Issue by Chasarr** [Ralim/ts100#741]
I found myself wondering what version my TS80P was running, and with no easy way on checking it on my soldering iron I instead flashed the firmware again. Adding a way of showing the soldering iron's version number seems like a good improvement

**Comment by Firebie** [comment]
There is a debug menu - with version number - on long press of second (from tip) button, menu items can be switched by first button.

**Comment by Chasarr** [comment]
I had a feeling that I overlooked _something_. Anyway I'll close the issue. Thanks
