### ISSUE TITLE
Not an Issue, Looking for a manual.

### ISSUE THREAD

**Issue by Doyle4** [Ralim/ts100#748]
Has any one got a link to a manual please? New to the soldering iron and installed the firmware soon as I got it today.

PID tuned, Voltage tuned and set it how id like it, but wondering what Gain is and how I can tell what gain goes to what tip.

Thanks :)

i purchased this one: https://www.amazon.co.uk/gp/product/B07G87H2FS/ref=ppx_yo_dt_b_asin_title_o01_s00?ie=UTF8&psc=1

Woah.. Glad I bought it yesterday when on offer... I never paid that for it.

**Comment by Ralim** [comment]
Hello 👋🏼 

There is no "manual" for this firmware as a complete set.
There are docs in [here](https://github.com/Ralim/ts100/tree/master/Documentation)
Around things that differ from the main firmware from Miniware but also the iron has descriptions on all of the settings, if you leave it paused on them for a bit. (Trying to put documentation in the firmware :) )

Generally leave everything in Advanced options alone unless you want to tweak it :)

**Comment by Doyle4** [comment]
@Ralim 
Thank you very much! So far so good, not used stock firmware, but your firmware was real nice to get around from the get go, thank you.
