### ISSUE TITLE
cannot upgrade

### ISSUE THREAD

**Issue by merwynv** [Ralim/ts100#77]
hi love your work, currently i have the APPV217.hex loaded on my soldering iron. i wanted to upgrade it, when i copy the DO NOT FLASH_Flash Backup.hex file onto the drive it disconnects and reconnects before copying the whole file and it does not show the empty drive space as well.  so when i click try again button it doesn't copy the file.

please help

**Comment by mikromCZ** [comment]
why you're flashing file named DO_NOT_FLASH?
just use https://github.com/Ralim/ts100/releases/download/v1.17/ts100.hex for update

**Comment by merwynv** [comment]
Done..... Thank you...
