### ISSUE TITLE
Low Volts on reasonable voltage

### ISSUE THREAD

**Issue by lukedempsey** [Ralim/ts100#81]
Hi, Im getting a low voltage when my voltage is at 16.3v on a 4s. Ive checked voltage calibration and its accurate

**Comment by Ralim** [comment]
Hi,
Can you confirm that the voltage remains stable under the full load of the iron (ie when heating from cold)? This is the most common issue of this occurring.

**Comment by Ralim** [comment]
@lukedempsey 
Is there any update to this ?

**Comment by lukedempsey** [comment]
Hi, 
Sorry for the late reply. Only just got around to testing. Yup it sags below the threshold, my mistake. 

Thanks
