### ISSUE TITLE
Dont know how to convert my bmp to hex

### ISSUE THREAD

**Issue by CrazyKoboldFPV** [Ralim/ts100#93]
Hi Guys. It´s no issue. But I don´t know how to convert my logo into the needen .hex. The Wiki is telling me I should use the application TS100.Logo.Editor.exe, but this exe I can´t find in any availible download.

Maybe someone could help me? Thanks guys.

**Comment by mikromCZ** [comment]
https://github.com/Ralim/ts100/releases/download/v1.15/TS100.Logo.Editor.exe

**Comment by CrazyKoboldFPV** [comment]
@mikromCZ Thank you very much. I did not find that exe. It was a stupid mistake of my. Next page... sorry. Thanks again.

**Comment by radioxoma** [comment]
Recent version https://github.com/Ralim/ts100/releases/download/v2.02/TS100.Logo.Editor.exe
