### ISSUE TITLE
Feature Request: adjustable time for logo

### ISSUE THREAD

**Issue by michael-blue2** [Ralim/ts100#99]
Is it really hard to make 1 more setting menu which will let you select how many seconds the logo will appear? :D

**Comment by Ralim** [comment]
On the list of things to change is to make it just dismiss with button press 😄 
Is that okay ?

**Comment by Ralim** [comment]
Okay, for now, I've made it wait 1 second or skip on button press. Thoughts ?

**Comment by michael-blue2** [comment]
Isnt it the default that comes with 1s? I think 2seconds will be perfect woth the skip aswel on button press:) sometimes you just want to show that logo around and the other times you just need to solder and dont care about it :)

**Comment by Ralim** [comment]
Sounds fair, I can bump it up to 2 seconds easily.

**Comment by michael-blue2** [comment]
perfect then :D, should i close the issue/request?

**Comment by tigert** [comment]
The show-until-buttonpress would be problematic because the idle image after the logo shows the hint for what button turns the iron on

**Comment by Ralim** [comment]
Show-until-buttonpress shows until either button is pressed and also 'consumes' that button press so it should not cause anything else to occur after its dismissed.
